fix(presenter): top menu anchor links are required to work on any page
dreammall-earth/dreammall.earth pull request #115
Opened 2023-12-19 14:03 UTC by mahula

## 🍰 Pullrequest

### Issues
- fixes #102 

### Todo

- [X] None

2023-12-19 14:17 UTC, Mogge requested changes
Does not work for me:

![image](https://github.com/dreammall-earth/dreammall.earth/assets/15882241/26146c24-0a99-4b01-bc56-a046f2a9bbed)

2023-12-19 14:28 UTC, Mogge submitted a review, later dismissed

2023-12-19 22:12 UTC, ulfgebhardt approved these changes

2023-12-20 07:31 UTC, mahula commented
Has been done in #121, too.

2023-12-20 07:31 UTC, closed without merging