feat(other): e2e test enter room
dreammall-earth/dreammall.earth pull request #1180
Opened 2024-06-17 19:31 UTC by mahula

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-06-21 11:27 UTC, Elweyn approved these changes

2024-06-21 14:13 UTC, roschaefer requested changes
![cucumber](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExem5uYXpwamZqc3p1MmJkZGFvYnBhNWt1Mjk4MTZxejZmM3phMW9rdyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ABfUsjhZyJDupR2Fz/giphy.gif)

What's the policy about blocking PR reviews with this team?

For me, I would click on request changes because of the cucumber test. It needs more specification by example, so I would like to see it improved before it gets merged. It goes without saying that I volunteer to help on it.

2024-06-21 14:13 UTC, roschaefer commented on tests/cypress/e2e/features/Tables.feature
> +    Then I am navigated to page where my room is queried
```suggestion
    Given I am signed in as a "user"
    And I have a personal room already
    When I click the "enter my room" button
    Then it will bring me to the website of my room
```

The login procedure is not relevant, just the role. For me the scenario doesn't really assert a lot of things but more importantly, it does not explain what the room feature is about?

2024-06-21 14:13 UTC, roschaefer commented on tests/cypress/e2e/pages/WorldcafePage.ts
> +    })
What's going on here? Could you explain this?

2024-06-21 14:13 UTC, roschaefer commented on tests/cypress/e2e/steps/tables.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
Why is eslint complaining so much in this PR?

2024-06-21 14:13 UTC, roschaefer commented on tests/package.json
> +    "cypress": "^13.12.0",
Unrelated

2024-06-22 19:23 UTC, mahula commented on backend/docker-compose.test.yml
> +version: '3.4'
Although the treatment of this warning is out of scope here, thank you for pointing it out.
This is handeld in #1248.

2024-06-24 20:31 UTC, mahula commented on tests/package.json
> +    "cypress": "^13.12.0",
Yes, but not harmful or to far off.
This package update is already in the master.

2024-06-25 17:33 UTC, mahula commented on .github/workflows/e2e.run.tests.yml
> +          sleep 2m
This has been taken care of in #1262

2024-06-25 17:41 UTC, mahula commented on .github/workflows/e2e.run.tests.yml
> +          docker compose -f docker-compose.test.yml up -d backend
Now backend and the frontends are run natively without `docker compose`.

2024-06-25 18:03 UTC, mahula commented on backend/docker-compose.test.yml
> +    image: it4c/backend:local-test
Yes, we started discussing that.
This will be taken care of in general in #1077.

2024-06-25 18:20 UTC, mahula commented on backend/docker-compose.test.yml
> +      - internal-net
Right.
Removed

2024-06-25 18:27 UTC, mahula commented on frontend/.env.dist
> +PUBLIC_ENV__AUTH__SCOPE="openid profile email"
Yes it is.
This was a left-over from removing aconfirmation step in Authentik.
What about leaving it here,since a separate PR do change it seprately might be a bit overkill. And from now on these kinda thing will be handled separately?

2024-06-25 18:43 UTC, mahula commented on tests/cypress/e2e/features/Tables.feature
> +  I want to enter the room reachable via the central worldcafe button
Good point,thank you.
THe WHY has been added with 6b1115fd916cb2b5e6b65660b118e249b49f6096.

2024-06-25 19:01 UTC, mahula commented on tests/cypress/e2e/features/Tables.feature
> +    Then I am navigated to page where my room is queried
This is also a good point.
For now, to increase the end-to-end coverage for the planned start version release, we decided to fix this in a side string of test improvement.
This will be taken care of soon.

2024-06-26 06:36 UTC, mahula commented on tests/cypress/e2e/pages/WorldcafePage.ts
> +    })
For the last test step `Then I am navigated to page where my room is queried` we check, if the right request was send.
The network intercepted needs to be done before the button click in `enterMyRoom()`.
That is the reason it is done in this method.
The intercept checks, if the request to the backend includes the `joinMyRoom` query. If so, the alias is set, which we wait for in the `Then I am navigated to page where my room is queried` step.

2024-06-26 07:07 UTC, mahula commented on tests/cypress/e2e/steps/tables.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
It is not this PR, it generally is about Cypress and Typescript.

2024-06-26 09:20 UTC, roschaefer requested changes
![delete](https://media1.tenor.com/m/LdvzCUIh5rcAAAAC/delete-trash.gif)

Remove the two obsolete files and the PR can be merged from my side.

2024-06-26 09:20 UTC, roschaefer commented on backend/Dockerfile
> +
```suggestion
```

This is not needed anymore, right?

2024-06-26 09:20 UTC, roschaefer commented on frontend/.env.dist
> +PUBLIC_ENV__AUTH__SCOPE="openid profile email"
Could you shine a light on why this is necessary? This does not only have an effect on testing, right?

2024-06-26 09:20 UTC, roschaefer commented on backend/docker-compose.test.yml
> +version: '3.4'
Also this file needs to be taken out of this PR.

2024-06-26 09:20 UTC, roschaefer commented on tests/cypress/e2e/pages/WorldcafePage.ts
> +    })
Ah, Ok. You can put this into the cucumber scenario.

2024-06-26 09:20 UTC, roschaefer commented on tests/cypress/e2e/features/Tables.feature
> +    Then I am navigated to page where my room is queried
```suggestion
    When I click the enter my room button
    Then a "POST" request is sent to the backend with the query params "?query=joinMyRoom"
```

The cucumber feature is technical documentation.

2024-06-26 09:58 UTC, mahula commented on backend/Dockerfile
> +
Good point. Done.

2024-06-26 10:02 UTC, mahula commented on backend/docker-compose.test.yml
> +version: '3.4'
Done

2024-06-26 11:54 UTC, mahula commented on frontend/.env.dist
> +PUBLIC_ENV__AUTH__SCOPE="openid profile email"
I removed this authentik-related change, because, right this is out of this PR's scope.

2024-06-26 12:25 UTC, roschaefer submitted a review, later dismissed

2024-07-01 08:27 UTC, roschaefer approved these changes

2024-07-01 08:27 UTC, roschaefer commented on tests/cypress/e2e/features/Tables.feature
> +    Then My room is queried
You can add some more explanation here what happens. It's sending a POST request right? If the audience is developers, then you can say it's sending a POST request to some URL with a payload. If the target audience is our clients, describe what the query is supposed to do. (If the audience is our clients, you could write this whole scenario in German)

2024-07-01 08:48 UTC, merged