feat(frontend): 709 5 navigation drawer component
dreammall-earth/dreammall.earth pull request #1185
Opened 2024-06-19 09:26 UTC by ogerly

PR 5: NavigationDrawer Component
Name: NavigationDrawer Component

frontend/src/components/menu/NavigationDrawer.vue
frontend/src/components/menu/NavigationDrawer.stories.ts
frontend/src/components/menu/NavigationDrawer.test.ts
frontend/src/components/menu/__snapshots__/NavigationDrawer.test.ts.snap

2024-06-19 14:49 UTC, Mogge commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +const validLocations = ['right', 'bottom', 'left', 'end', 'top', 'start'] as const
```suggestion
type validLocations = 'right' | 'bottom' | 'left' | 'end' | 'top' | 'start'
```

2024-06-19 14:49 UTC, Mogge commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +    type: String as () => (typeof validLocations)[number],
```suggestion
    type: String as () => (typeof validLocations)[number],
```
```suggestion
    type: String as () => validLocations,
```

2024-06-19 14:53 UTC, Mogge requested changes

2024-06-19 14:53 UTC, Mogge commented on frontend/tsconfig.json
> +    "baseUrl": ".",
What is this?

2024-06-19 14:53 UTC, Mogge commented on frontend/tsconfig.json
> +    "types": ["vite/client", "vitest/globals"],
Why is that needed?

2024-06-19 15:29 UTC, ogerly commented on frontend/tsconfig.json
> +    "types": ["vite/client", "vitest/globals"],
Vitest is a test framework, similar to Jest, that was developed specifically for projects that use Vite. The type definitions in vitest/globals make it possible to use global functions and variables provided by Vitest, such as describe, it, expect and others.

2024-06-19 15:32 UTC, ogerly commented on frontend/tsconfig.json
> +    "baseUrl": ".",
ich glaube das kann wieder weg. ich hatte es reingesetzt weil ich schauen wollte ob sich was ändert. die baseUrl wird als standart immer überall mit angegeben. aber wohl eher wichtig sollte dieser von "." abweichen. 
ich entferne es wieder.

2024-06-19 16:15 UTC, ogerly commented on frontend/tsconfig.json
> +    "baseUrl": ".",
deleted

2024-06-19 16:16 UTC, ogerly commented on frontend/tsconfig.json
> +    "types": ["vite/client", "vitest/globals"],
deleted

2024-06-20 14:42 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +})
```suggestion
const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  location: {
    type: String as PropType<NavigationDrawerLocation>,
    required: false,
    default: 'right',
    validator: (value: string) =>
      ['right', 'bottom', 'left', 'end', 'top', 'start'].includes(value as ValidLocation),
  },
})
```

2024-06-20 14:46 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +})
I suggest using `ValidLocation` as type and exporting it (hence the name change). Then we don't need the validator and the computedLocation can also be much simpler.

2024-06-21 12:40 UTC, Bettelstab requested changes
Please see comments.
Also you should write a test which checks that on mobile, the location will always be bottom, while on desktop it behaves like specified.

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +})
I think my suggestion here from last time went wrong. I meant:

```suggestion
export type DrawerLocation = 'right' | 'bottom' | 'left' | 'end' | 'top' | 'start'

const props = withDefaults(
  defineProps<{
    modelValue: boolean
    location?: DrawerLocation
  }>(),
  {
    location: 'right',
  },
)
```

I am fully aware that Vuetify internally does this in a different way (more like you do), but I think that's because they provide a library which could also be used by pure JS apps without Typescript support, and in that case it's the safer way to do it. And probably they still haven't updated their code to the new prop types notation.

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +    color="grey-lighten-4"
Maybe we don't want to override `grey` in dark mode. Possibly there is already a fitting color (for both themes) defined, if not, define a new theme color?

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +  background-color: #fff;
Why not use `bg-white`? Or something adapted to light/dark themes.

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +})
```suggestion
const computedLocation = computed(() => {
  return display.mobile.value
    ? 'bottom'
    : props.location
})
```

I don't think the additional check is necessary.

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +)
Possibly I', mistaken, but I thought this would happen automatically when you use v-model?! The purpose is just to keep the two values  (external / internal) in sync?

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +)
Ok I looked it up. The new recommended way is using defineModel(). I suggest:

```
const isOpen = defineModel<boolean>()
```

And renaming `drawer` to `isOpen` because that's what it is?

2024-06-21 12:40 UTC, Bettelstab commented on frontend/src/components/vuetify/NavigationDrawer.stories.ts
> +    location: 'left',
Add
```
modelValue: true,
```

2024-06-24 12:27 UTC, ogerly commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +    mobile
you're right, i'll remove it, it's not necessary at this point. 
here in the documentary you can see the property. 
https://vuetifyjs.com/en/api/v-navigation-drawer/#links

2024-06-24 12:47 UTC, ogerly commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +  background-color: #fff;
style removed

2024-06-24 12:47 UTC, ogerly commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +    color="grey-lighten-4"
color: removed

2024-06-24 12:47 UTC, ogerly commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +})
code adopted

2024-06-24 16:21 UTC, ogerly commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +)
rename from drawer to isOpen

2024-06-24 16:22 UTC, ogerly commented on frontend/src/components/vuetify/NavigationDrawer.vue
> +})
changed

2024-06-25 11:00 UTC, ogerly commented
i have lowered the coverage of the branch by 1%. if this PR is the first to enter the master, all others of mine that currently still have a red tick should be green.

2024-06-25 15:03 UTC, mahula commented
> i have lowered the coverage of the branch by 1%. if this PR is the first to enter the master, all others of mine that currently still have a red tick should be green.

Still the frontend linting check fails.

2024-06-25 16:45 UTC, Bettelstab commented
I still think you should use the `defineModel()` syntax as it is so much shorter.

2024-06-26 11:58 UTC, closed without merging