feat(frontend): add errorcase for join Roomquery
dreammall-earth/dreammall.earth pull request #1190
Opened 2024-06-20 06:25 UTC by trinity2701

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-06-20 14:52 UTC, Mogge approved these changes
Very clean PR. Good work!

2024-06-25 08:56 UTC, Mogge requested changes

2024-06-25 08:56 UTC, Mogge commented on frontend/src/pages/join-room/+Page.vue
> +    console.log('Error', error)
Please use the GlobalErrorHandler here to toast the error. See e.g. `/frontend/src/pages/signin/+Page.vue`

2024-06-25 10:22 UTC, Mogge approved these changes

2024-06-27 07:15 UTC, Elweyn approved these changes

2024-06-27 07:32 UTC, merged