fix(frontend): createbuttonmobile fix
dreammall-earth/dreammall.earth pull request #1194
Opened 2024-06-20 21:18 UTC by Bettelstab

## 🍰 Pullrequest
The button is now fully visible when it's open and the list is shown. Also adds a story, and fixes the one for BottomMenu (which was broken because of this button)

### Issues
- fixes part of #1173 

Suggestion for future work:
- I think the component is quite big and could be split into smaller ones, like one for the button ifself, one for the list, one for the wrapper
- Having a teleport target inside the Vue component tree seems to be not ideal, could be solved in a different way
- Better use Vuetify breakpoints instead of defining new ones

2024-06-21 10:16 UTC, Bettelstab commented
I think the failing tests are not related to this PR, but because of #1189

2024-06-21 19:10 UTC, roschaefer requested changes
![button](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGVtZ3NiaHlkcmlzdWplbWNucHZrYTZ5d2wzaGJhMWtkaWRzN20wZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/aihuG1Li9YrnXkJhpv/giphy.gif)

Alright I will also click on "Request changes" here. The biggest issue is that I don't see any difference except the circular border has changed a little. What do you mean with "The button is now fully visible"?

The biggest problem I have with this component is that it doesn't even *look* like a button for me.

![image](https://github.com/dreammall-earth/dreammall.earth/assets/2110676/4190b604-1e87-4b97-99ac-cc61fa54b609)

![image](https://github.com/dreammall-earth/dreammall.earth/assets/2110676/94dbd90f-4bcd-4872-8293-68fb0b536b38)

![image](https://github.com/dreammall-earth/dreammall.earth/assets/2110676/66d9107f-9f63-4de9-87f8-0bc0e8b0aa1f)

2024-06-21 19:10 UTC, roschaefer commented on frontend/src/components/menu/BottomMenu.stories.ts
> +  decorators: [
~Is this an unrelated change?~

Ok according to the PR description, it's indended. But I don't see anything broken on `origin/master`.

2024-06-21 19:10 UTC, roschaefer commented on frontend/src/components/menu/BottomMenu.stories.ts
> +  decorators: [
It also doesn't change anything on my screen when I revert it.

2024-06-23 11:54 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.vue
> -.button-wrapper {
We are using Vuetify, which brings components ready to use and its own set of utility classes. So I don't think it makes any sense to include tailwind as well.

2024-06-23 12:01 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.stories.ts
> +        '<div style="position: relative; height: 100vh; top: 25%;z-index: 10;"><div id="teleported"></div><story /></div>',
I just came up with a quick solution to make the story show something. The original code was not my work, and I didn't want to do more refactoring which was not planned for this sprint. I agree that this could be solved in a better way.

2024-06-23 12:02 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.stories.ts
> +        '<div style="position: relative; height: 100vh; top: 25%;z-index: 10;"><div id="teleported"></div><story /></div>',
Exactly my thoughts, again, the goal of this PR was not a complete refactoring.

2024-06-23 12:06 UTC, Bettelstab commented on frontend/src/components/menu/BottomMenu.stories.ts
> +  decorators: [
Did you try to hit the button on master?

2024-06-23 12:10 UTC, Bettelstab commented
Please have a look at the animations before and after the change. This is the main point of this PR. You could argue the stories are out of scope, I think there are nice to include because they demonstrate the change.

All further discussions can be lead, but imo they are out of scope for this PR.

2024-06-23 17:53 UTC, Bettelstab commented
PS: I added screenshots to clarify what the intended changes are.

2024-06-24 08:55 UTC, roschaefer approved these changes
If the only target of this PR was the animation, I can of course hit "approve" here. Nevertheless, I'd like to pair-program with someone in the frontend about the remaining issues.

Thanks for clarification! I also hit "request changes" if I don't understand a PR entirely. I saw the changes in the animation but didn't think it was the scope of the PR.

2024-06-24 11:21 UTC, Bettelstab commented
@roschaefer Thank you for all your feedback, it also reminds me to give more detailed information of what is a PR about.
I suggest you do a pair programming with @maeckes1 when he is back, otherwise I would also be open to do that with you.

2024-06-24 11:33 UTC, merged