build(deployment): local deployment
dreammall-earth/dreammall.earth pull request #1263
Opened 2024-06-25 16:28 UTC by roschaefer

Motivation
----------
On the weekend we had a downtime on production because `nginx` configurations got out of sync with the code in newer releases.

To prevent this and further downtimes I suggest to check in our deployment configuration and make it *reproducible*.

This PR is an attempt to create a docker container that behaves as similar as possible to production and can be used as a sandbox for changes to our deployment configuration.

Read about infrastructure as code: https://en.wikipedia.org/wiki/Infrastructure_as_code

How to test
-----------
1. `cd deployment`
2. `docker build . --tag dreammall-deployment`
3. `docker run -it -p 8080:80 dreammall-deployment sh` .. and wait
4. Following services are running:
  * http://localhost:8080/
  * http://localhost:8080/api
  * http://localhost:8080/docs
5. Be amazed

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-06-25 16:33 UTC, roschaefer commented
`docker ps --size` shows:
```
c915d6813f70   dreammall-deployment   "./entrypoint.sh sh"   12 minutes ago   Up 12 minutes   0.0.0.0:8080->80/tcp, :::8080->80/tcp   charming_shamir   2.66GB (virtual 3.11GB)
```

This is obviously way too big. We can get it smaller by e.g. de-duplicating node dependencies.

2024-06-25 16:36 UTC, roschaefer commented on deployment/Dockerfile
> +RUN git clone --depth 1 https://github.com/dreammall-earth/dreammall.earth.git /var/www/localhost/htdocs/dreammall.earth
This is a little silly. With a `.dockerignore` taking out `node_modules` we could `COPY` the content of the entire repository into the docker image.

2024-06-25 16:56 UTC, roschaefer commented
The only missing part here is the reverse proxy that forwards different stages, e.g. `dreammall.earth` or `stage1.app.dreammall.earth` to the container. I think this is fine to keep in mind. We can test things like `nginx.conf` files or `pnpm` in the docker container already.

2024-06-27 06:41 UTC, Elweyn reviewed
I had a problem with backend.
When I go on localhost:8080 and click on sign in I get on http://localhost:3000/signin instead of the frontend URL. (In presenter/.env it is defined to localhost:3000)

Except this it works. Goes in the right direction

2024-06-27 06:43 UTC, Elweyn requested changes

2024-06-27 06:43 UTC, Elweyn commented on deployment/Dockerfile
> +RUN cp frontend/.env.dist frontend/.env
Here we will need other values than the default ones

2024-06-27 15:33 UTC, roschaefer commented on deployment/Dockerfile
> +RUN cp frontend/.env.dist frontend/.env
This is actually a paint point that becomes visible through this PR. What are the right values for production? Is it documented anywhere?

2024-06-27 15:53 UTC, roschaefer commented
closed in favour of #1272

2024-06-27 15:53 UTC, closed without merging