feat(frontend): leave BBB room
dreammall-earth/dreammall.earth pull request #1265
Opened 2024-06-25 22:39 UTC by Bettelstab

## 🍰 Pullrequest
When the URL of the EmbeddedRoom iframe changes to `/` of the current origin, like the home page of our BBB instance, the iframe is removed and a redirect to the home page of the app is triggered.

### Issues
- fixes #706

2024-06-26 08:37 UTC, mahula requested changes

2024-06-26 08:37 UTC, mahula commented on frontend/src/components/embedded-room/EmbeddedRoom.vue
> +    emit('closed')
Please test the emit.

2024-06-26 10:05 UTC, Bettelstab commented on frontend/src/components/embedded-room/EmbeddedRoom.vue
> +    emit('closed')
Of course. I am still working on the tests.

2024-06-26 11:37 UTC, Mogge commented
@Bettelstab Please update the branch. The tests changed a lot

2024-06-26 17:12 UTC, Mogge requested changes
It does not work for me. The redirect is not triggered. The event `onRedirect` is never fired.

2024-06-26 21:11 UTC, Bettelstab commented
> It does not work for me. The redirect is not triggered. The event `onRedirect` is never fired.

I forgot to mention that to test this code locally, you have to change the iframe src by hand. (Or edit the iframe content and add a link.) Did you try something like that? 
Possibly I could come up with a better story to show this behavior...

2024-06-27 10:34 UTC, Elweyn requested changes
Tried it on stage1 and it does not work.
After clicking on konferenz close I get 
<img width="1911" alt="Screenshot 2024-06-27 at 12 33 40" src="https://github.com/dreammall-earth/dreammall.earth/assets/33051975/8f3f03f5-9c10-48ae-8e2e-92b44cb3476a">
After clicking on konferenz leave I get the same screen

2024-07-03 14:40 UTC, Bettelstab commented
=> Paused until we have subscriptions (#727)

2024-08-29 10:58 UTC, closed without merging