feat(frontend): show open rooms sidebar
dreammall-earth/dreammall.earth pull request #1273
Opened 2024-06-28 06:40 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- fixes #709

### Todo
- [X] None

2024-07-02 15:07 UTC, Elweyn reviewed
Top and BottomMenu have duplicate code.
Unit Test: 
- for ListElement should test the functionality
- for SearchField should test the functionality
- for ListWithNavigationDrawer test the functionality

2024-07-03 11:43 UTC, Bettelstab requested changes
(I don't want it to auto-merge, so I request changes)
Please see comments.
I can agree to do the refactoring and addition of more tests in a subsequent PR, but would suggest to do the smaller fixes right now before merging?

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Atoms/ListElement.vue
> +<template>
From the file name, I expected this to be a generally reusable component for a single element of a list. Should be named `RoomList.vue` instead.

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Atoms/ListElement.vue
> +        :key="index"
```suggestion
        :key="item.MeetingID"
```
Using index as key can lead to problems when the list is updated.

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Atoms/ListElement.vue
> +        :class="{ 'custom-list-item': true }"
```suggestion
        class="custom-list-item"
```

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Atoms/ListElement.vue
> +  items: {
Not super important, but I think we should use the newer Syntax everywhere:
https://vuejs.org/guide/typescript/composition-api#props-default-values

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Atoms/ListElement.vue
> +  */
Remove comment

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Molecules/SearchField.vue
> +)
```suggestion
const internalValue = defineModel<string>()
```

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/vuetify/Organisms/ListWithNavigationDrawer.vue
> +<template>
IMO this could be merged with `ListElement.vue` to `RoomList.vue` and we could remove a lot of code.

Otherwise: 
- Remove in fact unused location property
- Use defineModel() syntax
- Rename `drawer` to something more meaningful

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/stores/activeRoomStore.ts
> +    // console.log('setActiveRoom', room)
Remove

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/menu/TopMenu.vue
>                </Circle>
```suggestion
             <button class="camera-button" @click="toggleDrawer">
                <Circle>
                  <v-icon icon="$camera"></v-icon>
                </Circle>
              </button>
```

For accessibility and correct mouse cursor.

2024-07-03 11:43 UTC, Bettelstab commented on frontend/src/components/menu/BottomMenu.vue
>      </Circle>
```suggestion
             <button class="camera-button" @click="toggleDrawer">
                <Circle>
                  <v-icon icon="$camera"></v-icon>
                </Circle>
              </button>
```

For accessibility.

2024-07-03 11:53 UTC, Bettelstab commented
I can't comment in the code, because there was no change. But in `DefaultLayout.vue` line 17, we should remove the `class="d-md-none"` to avoid a warning, as `BottomMenu` doesn't have a single root element anymore to pass on the class property. The class is included in that file now, which is fine.
Besides, we could think about refactoring the code so that `ListWithNavigationDrawer` is only used once and not in both menus in the same way.

2024-07-03 14:52 UTC, Bettelstab commented on frontend/src/components/menu/BottomMenu.vue
> +}
Oh, I think this should not be here.

2024-07-04 06:28 UTC, Elweyn commented on frontend/src/components/menu/BottomMenu.vue
> +}
You are right if this is needed it should be in an own PR.

2024-07-05 09:50 UTC, Bettelstab approved these changes

2024-07-05 11:35 UTC, merged