build(workflow): same node version on all stages
dreammall-earth/dreammall.earth pull request #1319
Opened 2024-07-02 15:42 UTC by roschaefer

Motivation
----------
We have completely different `node --version`s on local development,
build server (even in different jobs) and production.

My suggestion is that we configure the node version in a central file in
the root folder and reference it from everywhere.

For me, any version manager is fine. If I have the choice, I suggest
[asdf-vm](https://github.com/asdf-vm/asdf).

How to test
-----------
1. Check status checks

2024-07-02 15:50 UTC, roschaefer commented on .tool-versions
> +nodejs 21.4.0
@Elweyn what's the version that we're using in production? On my vagrant machine on alpine 3.19 it's still `v18`.

2024-07-02 15:54 UTC, roschaefer commented on .tool-versions
> +nodejs 21.4.0
We checked and its also different between `production` and `staging`:
```
Prod: v20.11.1
Stage: v20.12.1
```

2024-07-02 15:56 UTC, roschaefer commented on .github/workflows/admin.deploy.chromatic.yml
> -      WORKING_DIRECTORY: ./admin
This is not related to `nodejs` but there is absolutely no reason why we should pollute `process.env` and have no benefit of another variable `WORKING_DIRECTORY` if we're using it only once.

2024-07-02 17:24 UTC, roschaefer commented on backend/package.json
> -  },
Version `>=21` is not even used in `production`, so let's do away with this.

2024-07-04 10:10 UTC, roschaefer commented on backend/package.json
> +    "node": ">=20"
That one is important for `eslint`.

2024-07-04 10:11 UTC, roschaefer commented on tests/package.json
> -    "node": ">=21"
That one was obsolete.

2024-07-04 10:14 UTC, roschaefer commented on package.json
> +    "@vuepress/theme-default": "^2.0.0-rc.35",
Unrelated, missing from #1325

2024-07-08 14:26 UTC, Mogge requested changes
One question: Does this mean, that every developer must use asdf?

2024-07-08 18:05 UTC, roschaefer commented
> One question: Does this mean, that every developer must use asdf?

No, it is completely up to the developer what they use. As written in the README just make sure that you use the node version specified in `tool-versions`. Use whatever version manager you like.

We just have to save the version in *some file*. Workflows shall take this file as a reference.

Good?

2024-07-09 07:48 UTC, Mogge approved these changes

2024-07-09 07:50 UTC, merged