refactor(other): remove vuepress in subfolders
dreammall-earth/dreammall.earth pull request #1325
Opened 2024-07-03 12:08 UTC by roschaefer

Motivation
----------
What actually gets deployed are the `docs` from the root folder. See the deployment script in [./deployment/scripts/build.docs.sh](./deployment/scripts/build.docs.sh).

There is no reason to have the `docs` dependencies, scripts, docker images, workflows for each subfolder, if we already have it in the root folder.

How to test
-----------
1. Nothing has changed. It just gets smaller, fast and DRYer.

2024-07-03 12:53 UTC, roschaefer commented on .github/workflows/test.code.yml
> +        run: npm install && npm run docs:build
This folder gets deployed but there was no workflow job for it.

2024-07-03 14:59 UTC, mahula requested changes

2024-07-03 14:59 UTC, mahula commented on .github/workflows/test.code.yml
>          run: npm install && npm test
Since `npm test` checks markdown file linting, but does not test any code, what about:

```
          filters: |
            docs:
              - '.github/workflows/**/*'
              - '**/*.md'
              - '.vuepress/*'
              - 'package.json'
            markdown:
              - '**/*.md'

  markdown:
    if: needs.files-changed.outputs.markdown == 'true'
    name: Lint Markdown Files
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Root | Lint Markdown Files
        run: npm install && npm test
```

2024-07-03 17:25 UTC, roschaefer commented on .github/workflows/test.code.yml
>          run: npm install && npm test
Addressed, thanks for the input!

2024-07-04 05:33 UTC, mahula approved these changes

2024-07-04 09:51 UTC, merged