fix(frontend): fix mobile create table
dreammall-earth/dreammall.earth pull request #1356
Opened 2024-07-07 11:18 UTC by Bettelstab

## 🍰 Pullrequest
Makes the mobile create button functionality to enter my room work again

### Issues
- fixes #1353

2024-07-07 22:55 UTC, roschaefer requested changes
![apollo](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHU0OGk0aDBldzcyN25vaXg2amV2NHR4bG9zaWM1cW1zZzZ1OXpmNSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UrPv5tJyTa7BYQobjx/giphy.gif)

I was about to hit "Approve" until I thought "Actually I would like to see a test case where they check that `navigate` is being called. There was a test but it's disabled.

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +          await wrapper.find('button.new-table-button').trigger('click')
We should use [testing-library](https://testing-library.com/) so we click on things the user can see here.

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +          joinMyRoomMutationMock.mockResolvedValue({
What about backend errors here:
```suggestion
          joinMyRoomMutationMock.mockResolvedValue({
            error: // ??
```

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +          expect(errorHandlerSpy).toBeCalledWith('No room found')
Under which circumstances can this happen?

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +            message: 'OUCH',
~This for sure will have `errors`, right?~

Looks like it's being handled further down and `mockRejectedValue` automatically returns the `errors` field.

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.vue
> +      navigate('/room/')
Why don't we have deep links?

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +        it.skip('navigates to room page', () => {
```suggestion
        it('navigates to room page', () => {
```

aaaand "Request changes"

2024-07-07 22:55 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +        it.skip('navigates to room page', () => {
We should have a linter rule protecting us from this.

2024-07-08 10:14 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +          await wrapper.find('button.new-table-button').trigger('click')
Sounds good.

2024-07-08 10:49 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.vue
> +      navigate('/room/')
Good point. I think we don't have the room / table id which belongs to the user. We could get if for sure. For the future, the mechanism as it is right now (with better abstractions and code reuse, for sure) could still be the best as it allows us to browse the DreamMall while staying in the meeting.

2024-07-08 10:50 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +        it.skip('navigates to room page', () => {
Ok I'll have a look into this. Was just copy pasted

2024-07-09 16:00 UTC, Bettelstab commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +          joinMyRoomMutationMock.mockResolvedValue({
Good question. I still don't know enough about error handling with Graphql to have an answer at hand, but will investigate...

2024-07-09 16:01 UTC, Bettelstab commented
I fixed the disabled tests and activated them.

2024-07-09 22:34 UTC, roschaefer approved these changes

2024-07-09 22:34 UTC, roschaefer commented on frontend/src/components/buttons/CreateButtonMobile.test.ts
> +          await flushPromises()
What promises are we waiting for here? It's best to have them inside the test case or wait for them in an async `before` hook.

2024-07-12 04:48 UTC, Elweyn approved these changes

2024-07-12 06:52 UTC, merged