feat(frontend): improve open tables drawer design
dreammall-earth/dreammall.earth pull request #1404
Opened 2024-07-11 22:40 UTC by Bettelstab

## 🍰 Pullrequest
Styles the open tables drawer according to Figma. Also adds messages in case of no open tables or no search results.

### Issues
- fixes #1171 

### Todo
-[ ] Set border color of search field depending on theme
-[ ] Avoid overlap with light/dark switch

2024-07-21 18:12 UTC, roschaefer requested changes
![so and so](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWxlZmJjNTh6enZ4eGQ2djRyZ25vbjN0dTJ5a2pwNzFxdW02dDI4eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/LOQTHurD6DegNX4oH7/giphy.gif)

I will request changes for the screenshot below:
![image](https://github.com/user-attachments/assets/90f0799e-2eb8-4081-90eb-eb7eaf5d93fd)

2024-07-21 18:12 UTC, roschaefer commented on frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
> +                    aria-label="Löschen"
I can see a `$t('tablesDrawer.noTables')` further down. So we're already translating the app, why not translate this, too?

2024-07-21 18:12 UTC, roschaefer commented on frontend/src/components/tablesDrawer/TablesDrawer.vue
> +    width: calc(100% - (2 * var(--sides))) !important;
The sheer amount of `!important`s in this block indicate a specificity problem.

2024-07-21 18:12 UTC, roschaefer commented on frontend/src/locales/de.json
>        "clear": "Löschen"
Why was this not used?

2024-07-21 18:12 UTC, roschaefer commented on frontend/src/components/tablesDrawer/TableList.vue
> +  <ul class="list">
I like that we're using plain HTML when possible :+1:

2024-07-21 22:33 UTC, Bettelstab commented on frontend/src/components/menu/TopMenu.vue
> +    v-if="!$vuetify.display.smAndDown"
Usually we use the Vuetify utility classes for cases like that: `d-none d-md-flex` but then we have to make an assumption of which display setting we want to use, which I dislike because of the tight coupling of supposed-to-be separate components. The other way around works better: `d-md-none` to hide things on medium size displays and above.
That's why I chose the JS solution here. But standard CSS can do the trick of course, just didn't think of that before. Will change it.

2024-07-21 22:35 UTC, Bettelstab commented on frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
> +      data-v-cf2c9067=""
This is what makes scoped CSS work. The tag is afaik generated from the file name or path.

2024-07-21 22:35 UTC, Bettelstab commented on frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
> +      style="bottom: 0px; z-index: 1004; transform: translateY(110%); position: fixed; transition: none !important; left: 0px; width: calc(100% - 0px - 0px);"
It's generated by Vuetify unfortunately.

2024-07-21 22:37 UTC, Bettelstab commented on frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
> +      style="right: 0px; z-index: 1004; transform: translateX(110%); position: fixed; height: calc(100% - 70px - 0px); top: 70px; bottom: 0px; transition: none !important;"
I have no explanation why it changed...

2024-07-21 22:38 UTC, Bettelstab commented on frontend/src/locales/de.json
>        "clear": "Löschen"
What do you mean? It's used in the search field.

2024-07-21 22:38 UTC, Bettelstab commented on frontend/src/components/tablesDrawer/TableList.vue
> +  <ul class="list">
:)

2024-07-22 10:20 UTC, Bettelstab commented on frontend/src/components/menu/TopMenu.vue
> +  z-index: 1008;
I agree. Just had a quick look at https://www.smashingmagazine.com/2021/02/css-z-index-large-projects and the idea makes sense to me. We are dealing with Vuetify values here, I'll check if there is any way to get those values.

2024-07-22 10:21 UTC, Bettelstab commented on frontend/src/components/tablesDrawer/TablesDrawer.vue
> +    width: calc(100% - (2 * var(--sides))) !important;
Vuetify components that we need to override :/

2024-07-22 10:22 UTC, Bettelstab commented
I'll address some of the issues you mentioned. Your main point: There is the plan to move the Light/Dark switch from where it is to some settings menu, therefore we decided to ignore this problem.

2024-07-22 11:51 UTC, Bettelstab commented on frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
> +                    aria-label="Löschen"
We are translating this, of course. Apparently the Vuetify internal dictionary entries are resolved for the snapshots. That's a strange behaviour and could lead to problems in CI. Good catch. 
Why does it appear now: I corrected the keys in the locales files.

2024-07-22 11:56 UTC, Bettelstab commented on frontend/src/components/menu/TopMenu.vue
> +  z-index: 1008;
I simplified the structure. Was like that before because of requirements which changed.

2024-07-22 11:58 UTC, Bettelstab commented
@roschaefer 
Please have another look :) Guess we should create an issue for the vuetify translation thing

2024-07-23 13:34 UTC, roschaefer commented on frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
> +      style="bottom: 0px; z-index: 1004; transform: translateY(110%); position: fixed; transition: none !important; left: 0px; width: calc(100% - 0px - 0px);"
Again generated code. But what the heck, Vuetify, style attributes, seriously? They have the highest specificity: https://2019.wattenberger.com/blog/css-cascade#specificity

![disappointed](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmVzajVmZzhxOGF4MHpoYjRucnl5aWhuMXZraXd0N2Fjdm5nN2c4cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BKnKdJjiJrAGSTGzgM/giphy.gif)

2024-07-23 13:34 UTC, roschaefer commented on frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
> +      style="right: 0px; z-index: 1004; transform: translateX(110%); position: fixed; height: calc(100% - 70px - 0px); top: 70px; bottom: 0px; transition: none !important;"
Sorry for that, if it's generated, I pretty much don't care about the order here.

2024-07-23 13:35 UTC, roschaefer commented on frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
> +                    aria-label="Löschen"
Yes! It's *good* that it's translated now :slightly_smiling_face: the problems in unit testing is another story.

2024-07-23 13:40 UTC, roschaefer commented on frontend/src/components/tablesDrawer/TablesDrawer.vue
> +    width: calc(100% - (2 * var(--sides))) !important;
> Vuetify components that we need to override :/

This is *exactly* the selling point of Tailwind. No more specificity wars. Every component framework that is built on Tailwind is using the *same level* of specificity. Every template code that we copy+paste will look the same in our application as it does in a sandbox. The nesting template will only pass in CSS that is not specified in the inner template.

Problems *solved*. Once. And. For. All.

2024-07-23 13:58 UTC, roschaefer approved these changes
![image](https://github.com/user-attachments/assets/a8e853f4-9afc-4f6f-8266-68c4a48cfc0a)

We could give the light/dark switch a white outline, just like the other buttons.

I will hit approve here to get things going though.

I'm afraid this won't be the last PR where I will complain about vuetify.

2024-07-23 13:58 UTC, roschaefer commented on frontend/src/components/menu/TopMenu.vue
> +.hide-on-mobile {
This is such a utility class. It shouldn't go into `scoped`. I think in tailwind it would be `invisible md:visible`.

2024-07-23 18:47 UTC, Bettelstab commented on frontend/src/components/menu/TopMenu.vue
> +.hide-on-mobile {
Yes, I totally agree and will make it global with a better name the next time I'll use it. No, visibility is something different and takes rendering time.

2024-07-23 18:53 UTC, merged