fix(frontend): pass required props to message and news indicator in tests
dreammall-earth/dreammall.earth pull request #1406
Opened 2024-07-12 11:31 UTC by Bettelstab

## 🍰 Pullrequest
Makes those little warnings go away:

<img width="567" alt="Screenshot 2024-07-12 at 13 22 12" src="https://github.com/user-attachments/assets/890487d2-27d6-4bdf-9331-d6b92c480cda">
<img width="738" alt="Screenshot 2024-07-12 at 13 22 19" src="https://github.com/user-attachments/assets/56dd0152-31b3-4546-a775-2f34aca1a47c">

2024-07-15 22:17 UTC, roschaefer approved these changes
![brush](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExanF4a250a3lvbmtxcndrdWR3MmgzM2xlYWk2OWw0YzIzM2o4bWlyciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QA6E6Ejy4nBguvZykF/giphy.gif)

Here's a little suggestion.

2024-07-15 22:17 UTC, roschaefer commented on frontend/src/components/menu/MessageIndicator.test.ts
> +    return mount(MessageIndicator, { props: { numberOfMessages: 1 } })
How about:
```suggestion
  const Wrapper = (opts={ props: { numberOfMessages: 1 } }) => {
    return mount(MessageIndicator, opts)
  }
```

And then calling it from the test instead of the `before` hook.

2024-07-17 08:48 UTC, Mogge requested changes

2024-07-17 08:48 UTC, Mogge commented on frontend/src/components/menu/MessageIndicator.test.ts
> +    wrapper = Wrapper({ props: { numberOfMessages: 2 } })
```suggestion
    wrapper = Wrapper({ props: { numberOfMessages: 0 } })
```
according to the it statement?

2024-07-18 11:21 UTC, Mogge approved these changes

2024-07-18 17:35 UTC, merged