fix(backend): endless redirects
dreammall-earth/dreammall.earth pull request #1502
Opened 2024-07-21 00:14 UTC by roschaefer

Motivation
----------
This is a side quest of #1451.

If there is an error with the prisma client, we send `UNAUTHENTICATED` instead of `INTERNAL_ERROR`. This will lead to an endless loop because the frontend redirects to `/signin` over and over again.

I also made a refactoring: I want to be able to mock the prisma client, so that it rejects with an error. It is a best practice to use the `dataSources` pattern from Apollo <= v2:
https://www.apollographql.com/docs/apollo-server/v2/data/data-sources/

In Apollo v4 you simply put it into `context`. I like the name `dataSources` though and nested the `prisma` client in there.

How to test
-----------
1. `docker compose down database -v`
2. `docker compose up database backend frontend authentik`
3. Login in at http://localhost:3000/
4. No endless redirects

ToDos
-----
- [ ] As a follow up we should make sure to always use the `prisma` client from the `context`. But I'll leave this for another day.

2024-07-21 00:15 UTC, roschaefer commented on backend/src/auth/authChecker.ts
> -  } catch {
There was no real reason why we want to catch *any* error here, right?

2024-07-21 09:43 UTC, roschaefer commented on backend/src/auth/authChecker.ts
> -  } catch {
In general it is not a great idea to have a catch-all block. One should always check the error and if it's not the expected error class, re-throw.

Here's an eslint plugin illustrating the problem:
https://www.npmjs.com/package/eslint-plugin-no-catch-all

2024-07-22 09:43 UTC, Mogge requested changes
I like this. Looking forward to see the dataSource used in the resolvers as well. Some small things ...

2024-07-22 09:43 UTC, Mogge commented on backend/src/auth/authChecker.ts
> +    const user = await contextUser(prisma)(nickname, name)
This was inside the catch block, because the `contextUser` function may fail

2024-07-22 09:43 UTC, Mogge commented on backend/src/auth/authChecker.ts
> +    void EVENT_CREATE_USER(user.id)
Better await here? This may lead to flaky unit tests

2024-07-22 09:43 UTC, Mogge commented on backend/src/auth/authChecker.spec.ts
> +        const expected = {
I do not like this construction. I really prefer to see this inside the `toEqual` in the expect part

2024-07-23 15:12 UTC, Mogge approved these changes

2024-07-23 15:13 UTC, merged