feat(authentik): seed authentik via blueprints
dreammall-earth/dreammall.earth pull request #1510
Opened 2024-07-22 15:23 UTC by roschaefer

Motivation
----------
Blueprints are the authentik-native approach for automated configuration: https://docs.goauthentik.io/developer-docs/blueprints/

*Of course* a postgres DB dump cannot be the setup for a new instance. Things like URLs would differ and it's impossible to template a Postgresql dump. But templating a blueprint *is*.

This PR is necessary for #1451 and basically any automated deployment.

In the future we should develop authentik flows via the blueprints *and not through the UI* - this is not reproducible.

How to test
-----------
1. `cd authentik && docker compose up`
2. Wait for a certain amount of time, the `authentik-worker` has a lot to do initially.
3. Visit http://localhost:9000/if/admin/#/flow/flows;%7B%22search%22%3A%22dreammall%22%7D
4. Login with `akadmin` and password `dreammall`
5. The 5 dreammall flows are there.

Todo
----
- [ ] Setup the frontend application
- [ ] Setup the OpenID provider
- [ ] Set blueprint callback URLs via `ENV`s to the ones in `frontend/.env`
- [ ] As soon as we have parity with the database seed we can remove any of the example flows that we don't need.

2024-07-22 15:24 UTC, roschaefer commented on authentik/blueprints/system/bootstrap.yaml
> +  password: !Env [AUTHENTIK_BOOTSTRAP_PASSWORD, null]
This one is set in our `authentik/docker-compose.override.yaml`

2024-07-22 15:25 UTC, roschaefer commented on authentik/blueprints/dreammall/dreammallearth-authentication-flow.yaml
> +    name: dreammall-authentication-flow-password-stage
Whenever the import would fail because of a uniqueness constraint of a `name` I would simply call it `dreammall-...` even though the flow is a copy+paste from one of the already existing default flows.

2024-07-22 15:26 UTC, roschaefer commented on authentik/blueprints/dreammall/dreammallearth-authentication-flow.yaml
> +    configure_flow: !Find [authentik_flows.flow, [slug, default-password-change]]
I matched this line with the corresponding default flow.

2024-07-22 15:27 UTC, roschaefer commented on authentik/blueprints/dreammall/dreammallearth-enrollment.yaml
> +    name: dreammall.earth-redirect-localhost-frontend-signin
We have `enrollment` and `enrollment-email` and the two flows point to `localhost` and `stage1.app.dreammall.earth` is it possible that these two should be the same with different values?

2024-07-22 15:29 UTC, roschaefer commented on authentik/docker-compose.override.yml
> +      - ./blueprints:/blueprints
This will do all the magic.

2024-07-26 14:55 UTC, roschaefer commented on .github/workflows/e2e.run.tests.yml
> -          docker compose exec -T postgresql psql authentik --username authentik < authentik/dump.sql
Seeds are gone here. `authentik-worker` will turn healthy once all blueprints are applied.

2024-07-26 14:59 UTC, roschaefer commented on authentik/blueprints/dreammall/dreammallearth-enrollment.yaml
> +    name: dreammall.earth-redirect-localhost-frontend-signin
Now I get it that the `PUBLIC_ENV__AUTH__AUTHORITY_SIGNUP_URI` from `frontend/.env` points to the URLs of these enrollment flows and can be configured differently for local development and production.

2024-07-28 22:27 UTC, roschaefer commented on .github/workflows/e2e.run.tests.yml
> -          docker compose exec -T postgresql psql authentik --username authentik < authentik/dump.sql
So `docker-compose up authentik authentik-worker -d --wait` will go to background when the blueprints are ready.

2024-08-01 02:04 UTC, mahula requested changes

2024-08-01 02:04 UTC, mahula commented on authentik/README.md
> +Wait for some minutes and and open [http://localhost:9000](http://localhost:9000).
```suggestion
Wait for some minutes and open [http://localhost:9000](http://localhost:9000).
```

2024-08-01 11:47 UTC, Mogge approved these changes

2024-08-01 11:53 UTC, merged