feat(frontend): user store
dreammall-earth/dreammall.earth pull request #1525
Opened 2024-07-24 16:09 UTC by Mogge

## 🍰 Pullrequest
User store to store information of the current user including the table of the current user and the users that may see the table of the current user

### Issues

- None

### Todo

- [X] None

2024-07-31 17:02 UTC, Bettelstab requested changes
Meanwhile `room` was changed to `table`, so this needs to be done here as well. Otherwise tested and approved.

2024-08-01 04:52 UTC, mahula approved these changes

2024-08-01 11:50 UTC, Bettelstab approved these changes

2024-08-01 16:15 UTC, mahula approved these changes

2024-08-01 17:36 UTC, merged