feat(backend): events for create and update my table
dreammall-earth/dreammall.earth pull request #1584
Opened 2024-07-30 14:31 UTC by Mogge

## 🍰 Pullrequest
To have track of user activity we want to have events for all mutations stored in the database. This PR adds the mssing events for create and update my table.

### Issues

- None

### Todo

- [X] None

2024-07-30 22:23 UTC, roschaefer requested changes
@Mogge could you elaborate a little on why we need this?

I would also love to see a more generic solution to this. How about logging every database call? Or logging every database call we're interested in?

Most importantly: It is generally a bad idea to use the database as a log stream. A better solution is, surprise, a log stream. Since we have the respective methods in-place, we should be able to refactor this easily, correct?

![log lady](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExamF2ZXFmNjltOXBhcHJpcG8ydDZ2N3c0MDFpcW1pcDUza3pid2NkeCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3otPoxy3BE4iPS0RYA/giphy.gif)

2024-07-30 22:23 UTC, roschaefer commented on backend/src/event/EventType.ts
> +  CREATE_MY_TABLE = 'CREATE_MY_TABLE',
I would expect that the event type defines the payload that needs to be passed as argument.

2024-07-30 22:23 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +          const user = await prisma.user.findFirst()
Could we use hard-coded assertion values here, please?

2024-07-30 22:23 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it('creates create my table event in the database', async () => {
```suggestion
        it('logs event `CREATE_MY_TABLE`', async () => {
```

We could also specify the payload here.

2024-07-30 22:23 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it('creates update my room event', async () => {
```suggestion
        it('logs event `UPDATE_MY_TABLE`', async () => {
```

2024-07-31 08:17 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it('creates create my table event in the database', async () => {
This is not meant as a log. The purpose is, that admins can see the activity of certain users, e.g. to provide the support with information concerning the user asking for help. Furthermore, you can easily generate statistics of the usage of the application. Doing this by a database log is much harder to achieve.

2024-07-31 08:18 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +          const user = await prisma.user.findFirst()
At this point, there is only one user in the DB. But you are right.

2024-07-31 08:19 UTC, Mogge commented on backend/src/event/EventType.ts
> +  CREATE_MY_TABLE = 'CREATE_MY_TABLE',
This would be a refactor, if we decide to do so, and therefore out of scope of this PR.

2024-07-31 08:26 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it('creates create my table event in the database', async () => {
Does this answer your question?

2024-07-31 09:09 UTC, roschaefer approved these changes

2024-07-31 09:11 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it('creates create my table event in the database', async () => {
Alright, I've hit approve. Fine with me to save it to the database if "admins" are non-technical admins. But we have no UI for this yet, right?

2024-08-01 11:16 UTC, merged