feat(frontend): deep link for table page
dreammall-earth/dreammall.earth pull request #1592
Opened 2024-07-31 09:03 UTC by Mogge

## 🍰 Pullrequest

### Issues
- fixes #1581 

### Todo

- [X] None

2024-07-31 17:51 UTC, Bettelstab requested changes
join-room links don't work, fix see comment.
The corresponding test needs to be fixed as well.
In general, types for all query responses would be nice.

2024-07-31 17:51 UTC, Bettelstab commented on frontend/src/pages/join-table/+Page.vue
> +      window.location.href = joinTableAsGuestQueryResult.value.joinTable
```suggestion
      window.location.href = joinTableAsGuestQueryResult.value.joinTableAsGuest
```

2024-08-01 11:15 UTC, Mogge commented on frontend/src/pages/join-table/+Page.vue
> +      window.location.href = joinTableAsGuestQueryResult.value.joinTable
Good Catch!

2024-08-01 11:52 UTC, Bettelstab approved these changes

2024-08-01 15:43 UTC, Bettelstab approved these changes

2024-08-02 10:21 UTC, Bettelstab approved these changes

2024-08-02 10:23 UTC, merged