refactor(frontend): refactor merging of top menu and bottom into default layout
dreammall-earth/dreammall.earth pull request #1596
Opened 2024-08-01 09:38 UTC by sebastian2357

## 🍰 Pullrequest

- extracted/split DreamMallButton from business logic
- renamed "create-button" to DreamMallButton
- merged Bottom- and TopMenu into DefaultLayout
- elimated duplicated code
- simplified structure
- fixed tests
- reduced TablesDrawer to one
- enhanced TablesDrawer to handle its orientation switch better

### Issues

- #1579 

### Todo

- [X] None

2024-08-01 16:39 UTC, Bettelstab requested changes
- The dreammall button actions cannot be in the default slot, otherwise they will just be overridden by any page with actual content (currently the index page does not have content...) That is the most important.
- Naming should be consistent. If you think it's too much for now, better revert it IMO and do it later.
- The DefaultLayout test file needs at least some cleanup, to not have several identical snapshots

2024-08-01 16:39 UTC, Bettelstab commented on frontend/src/layouts/DefaultLayout.test.ts
> +      expect(wrapper.element).toMatchSnapshot()
Doesn't make sense since the BottomMenu does not exist anymore, this will just render the whole DefaultLayout. I think the approach with testing for different screen sizes is great, but there were problems?

2024-08-01 16:39 UTC, Bettelstab commented on frontend/src/layouts/DefaultLayout.vue
> +        <div class="create-button-container">
What is the intention behind putting this into the slot element?

2024-08-01 16:39 UTC, Bettelstab commented on frontend/src/layouts/DefaultLayout.vue
> +  }
I'm quite sure this try catch is not necessary

2024-08-01 16:39 UTC, Bettelstab commented on frontend/src/layouts/DefaultLayout.vue
> +      </MainButton>
I think this should be in its own file as before, and there should be a slot for it so we can specify per page which dreammall button actions are available. The whole DefaultLayout is now so big... But for me it's fine if it will shrink again in future PRs.

2024-08-01 16:39 UTC, Bettelstab commented on frontend/src/layouts/DefaultLayout.vue
> +.create-button-container {
Inconsistent naming also in some classes here

2024-08-01 16:40 UTC, Bettelstab commented on frontend/src/components/tablesDrawer/TablesDrawer.vue
> +  transition: isChangingOrientation.value ? 'none' : undefined,
Hmm. I removed the computed style and it makes no difference for me. Are you sure it has an effect? Otherwise I propose to not invest more time now in this and create a ticket for later. It's such an edge case.

2024-08-02 10:57 UTC, sebastian2357 commented on frontend/src/layouts/DefaultLayout.vue
> +        <div class="create-button-container">
It was indeed the implementation before. it should have the same behaviour now, but yeah it can not be right, but this should be handled in an another ticket. 

BTW the way this was the reason to ask about the dream mall button concept.

2024-08-02 10:59 UTC, sebastian2357 commented on frontend/src/layouts/DefaultLayout.vue
> +  }
Absolutely, have not seen it.

2024-08-02 11:01 UTC, sebastian2357 commented on frontend/src/layouts/DefaultLayout.vue
> +      </MainButton>
it depends on the concept of the DreamMallButtons. Should it not fit to here, I would move it out again.

2024-08-02 11:12 UTC, sebastian2357 commented on frontend/src/components/tablesDrawer/TablesDrawer.vue
> +    :class="['menu-drawer px-4', { 'changing-orientation': isChangingOrientation }]"
thanks

2024-08-02 11:13 UTC, sebastian2357 commented on frontend/src/components/tablesDrawer/TablesDrawer.vue
> +// New reactive properties for handling orientation changes
actually I wanted to remove it completly before pushing  it

2024-08-02 11:17 UTC, sebastian2357 commented on frontend/src/layouts/DefaultLayout.test.ts
> +      expect(wrapper.element).toMatchSnapshot()
indeed!

2024-08-02 14:21 UTC, Bettelstab commented on frontend/src/components/buttons/LargeDreamMallButton.vue
> +const click = (event: MouseEvent) => {
onClick was fine for the handler, just not for the emitted event ;)

2024-08-07 11:57 UTC, Bettelstab approved these changes
Better remove the VContainer, but anyway

2024-08-07 11:57 UTC, Bettelstab commented on frontend/src/layouts/DefaultLayout.vue
> +    <v-container fluid class="page-container px-8">
```suggestion
    <div class="page-container px-8">
```
VContainer is a part of Vuetify's grid system, which we are not using here.
https://vuetifyjs.com/en/components/grids/

2024-08-07 18:27 UTC, Bettelstab approved these changes

2024-08-07 18:27 UTC, merged