Implementation of the basic structure and authentication for the admin area
dreammall-earth/dreammall.earth pull request #1672
Opened 2024-08-04 15:42 UTC by ogerly

## 🍰 Pullrequest

This pull request implements the basic structure and authentication for the admin area of DreamMall. The main changes include:

- Introduction of authentication logic with Pinia Store (auth.ts)
- Implementation of login and logout functionality
- Development of components for the user interface:
  - LoginForm.vue: form for user login
  - SideMenu.vue: Sidebar for the main navigation
  - NavBarTop.vue: Top navigation bar
  - DefaultLayout.vue: Default layout for admin pages
- Integration of Vuetify for the UI design

Changed files:
- README.md: Update of the project documentation
- admin/renderer/+onRenderHtml.ts: Adjustments for SSR
- admin/src/assets/img/dreammall-logo.svg: New project logo
- admin/src/components/PageShell.vue: Basic component for page layout
- admin/src/components/forms/LoginForm.vue: Implementation of the login form
- admin/src/components/menu/LogoAvatar.vue: Component for user avatar
- admin/src/components/menu/NavBarTop.vue: Top navigation bar
- admin/src/components/menu/SideMenu.vue: Side menu with login/logout functionality
- admin/src/layouts/DefaultLayout.vue: Default layout for admin pages
- admin/src/pages/_error/+title.ts: Error page title
- admin/src/pages/about/+title.ts: Title for about page
- admin/src/pages/app/+onBeforeRender.ts: Auth check for protected routes
- admin/src/pages/app/+Page.vue: Main page of the admin area
- admin/src/pages/app/+title.ts: Title for admin main page
- admin/src/pages/index/+Page.vue: Home page with login form
- admin/src/stores/auth.ts: Pinia Store for authentication

These changes lay the foundation for the admin area and enable secure authentication and basic navigation. Additional features and refinements will be implemented in future PRs.

Translated with DeepL.com (free version)

### Issues
- fixes #1670

2024-08-04 15:57 UTC, ogerly commented
https://github.com/user-attachments/assets/e29a92c2-f718-4691-be8d-ffbc3ed5a5ae

2024-08-04 16:03 UTC, ogerly commented
https://github.com/user-attachments/assets/2cd367a3-8aa7-4658-9c1a-0fbcffa3449b

2024-08-05 08:58 UTC, roschaefer requested changes
![image](https://github.com/user-attachments/assets/c9377e47-82c0-4d25-a4a5-37fe69a6028c)

![image](https://github.com/user-attachments/assets/9b835b0a-d536-45b9-8710-7091df1233df)

![image](https://github.com/user-attachments/assets/592e36c2-b8f5-4378-902c-7b2df28c4483)

![image](https://github.com/user-attachments/assets/97392d9e-350b-4943-948c-5f690d9798d4)

Please remove files:
```
admin/src/stores/counter.ts
admin/src/stores/counter.test.ts
```


Looks pretty good! All my changes are optional except the `v-if`s on the authentication state. You should have checks per *page*. I think all pages could redirect to authentik if you're not logged in.

2024-08-05 08:58 UTC, roschaefer commented on admin/src/components/menu/LogoAvatar.vue
> +  :src=Logo
```suggestion
  :src="Logo"
```
Bug?

2024-08-05 08:58 UTC, roschaefer commented on admin/src/components/menu/NavBarTop.vue
> +          </v-btn> -->
```suggestion
```

2024-08-05 08:58 UTC, roschaefer commented on admin/src/components/menu/NavBarTop.vue
> +  <script lang="ts" setup>
```suggestion
</template>
<script lang="ts" setup>
```

2024-08-05 08:58 UTC, roschaefer commented on admin/src/components/menu/SideMenu.vue
> +    </v-list>
```suggestion
    <v-list>
      <v-list-item
        prepend-avatar="https://randomuser.me/api/portraits/women/85.jpg"
        :title="Erika Musterfrau"
      ></v-list-item>
    </v-list>
```

The entire sidebar should not get rendered if you're not authenticated. There is nothing that you can do with it otherwise.

2024-08-05 08:58 UTC, roschaefer commented on admin/src/components/menu/SideMenu.vue
> +  window.location.href = '/'
Use proper links! This is important for accessibility.

2024-08-05 08:58 UTC, roschaefer commented on admin/src/components/menu/SideMenu.vue
> +<script lang="ts" setup>
You can remove the entire `<script>` part as soon as the sidebar does not need to check logged in state anymore.

2024-08-05 08:58 UTC, roschaefer commented on admin/src/pages/app/+Page.vue
> +        </v-list-item>
```suggestion
```
Could we please just display fields that we have? I don't remember any way to save a phone number or postal address as a user.

2024-08-05 08:58 UTC, roschaefer commented on admin/src/pages/app/+Page.vue
> +    <v-container fluid v-if="authStore.$state.isLoggedIn">
```suggestion
    <v-container fluid>
```

Why?

2024-08-05 08:58 UTC, roschaefer commented on admin/src/pages/app/+Page.vue
> +      v-if="authStore.$state.isLoggedIn"
```suggestion
```

2024-08-05 08:58 UTC, roschaefer commented on admin/src/pages/index/+Page.vue
> +            Userübersicht
```suggestion
            Benutzer-Übersicht
```

2024-08-05 08:58 UTC, roschaefer commented on admin/src/stores/auth.ts
> +      console.log('useAuthStore: Logged in', this.isLoggedIn)
We would redirect to authentik here, right?

2024-08-15 06:58 UTC, ulfgebhardt commented
We decided against the admin interface with the employer for now

2024-08-15 06:58 UTC, closed without merging