1656 integration von parallax starry sky example
dreammall-earth/dreammall.earth pull request #1673
Opened 2024-08-04 20:40 UTC by ogerly

## 🍰 Pullrequest
# Starry Map Component Documentation

## Overview
The Starry Map component creates an interactive, scrollable and zoomable universe-like interface. It displays a parallax background with multiple layers and an interactive layer of "stars" representing various virtual spaces or users.

## Component Structure

### Template
- `<div class="universe-viewport">`: Main container for the entire map.
- `<div class="background-layers">`: Contains parallax background layers.
- `<div class="interactive-layer">`: Contains interactive star elements.
- `<div class="info-box">`: Displays information about a selected star.
- `<div class="controls">`: Contains zoom controls and position information.

### Script
- `data()`: Defines reactive data properties.
- `computed`: Contains computed properties.
- `mounted()`: Lifecycle hook for initializing the component.
- `methods`: Contains all component methods.

### Style
Scoped styles for the component.

## Key Features

1. **Parallax Background**: Multiple layers moving at different speeds to create depth.
2. **Interactive Stars**: Clickable elements representing virtual spaces or users.
3. **Zoom Functionality**: Ability to zoom in and out of the map.
4. **Draggable Navigation**: Click-and-drag navigation within the map.
5. **Star Information**: Clickable stars reveal detailed information.

## Main Methods

- `generateStars()`: Creates an array of star objects with random properties.
- `getLayerStyle(index)`: Calculates the style for each background layer based on scroll position.
- `getInteractiveLayerStyle()`: Calculates the style for the interactive layer.
- `handleWheel(e)`: Handles mouse wheel events for zooming.
- `setZoom(level)`: Sets the zoom level.
- `showInfo(star)`: Displays information about a selected star.
- `startDrag(event)`, `drag(event)`, `stopDrag()`: Handle dragging functionality.

## TODOs

1. **Implement Star Clusters for Categories**
   - Group stars into clusters based on categories.
   - Implement visual representation for clusters.
   - Add interaction methods for clusters.

2. **Arrange Clusters into Constellations**
   - Design and implement constellation patterns.
   - Assign stars to specific constellations.
   - Add visual elements to represent constellation shapes.

3. **Enhance Space Depth**
   - Increase the number of parallax layers.
   - Implement a more sophisticated depth calculation for star positioning.
   - Add visual effects (e.g., fog, size variation) to enhance depth perception.

4. **Optimize Navigation**
   - Implement smooth scrolling and zooming animations.
   - Add boundaries or wrap-around effect for map edges.
   - Optimize performance for handling a large number of stars.

5. **Create Storybook Story**
   - Develop a comprehensive Storybook story showcasing different states and interactions.
   - Include examples of various zoom levels, star densities, and cluster arrangements.

6. **Implement Testing**
   - Write unit tests for core methods (e.g., `generateStars`, `getLayerStyle`).
   - Implement integration tests for user interactions (click, drag, zoom).
   - Set up end-to-end tests to ensure overall functionality.

## Usage

```vue
<template>
  <StarryMap />
</template>

<script>
import StarryMap from './components/StarryMap.vue'

export default {
  components: {
    StarryMap
  }
}
</script>
```

## Props
Currently, the component does not accept any props. Future iterations may include props for customization.

## Events
The component currently does not emit any custom events. Consider adding events for significant interactions in future versions.

## Performance Considerations
- The component may become performance-intensive with a large number of stars.
- Consider implementing virtual scrolling or lazy loading for improved performance with large datasets.

## Accessibility
- Keyboard navigation and screen reader support should be implemented in future iterations.

## Browser Compatibility
- Tested on modern browsers (list specific versions in future documentation).
- May require polyfills or additional handling for older browsers.

This documentation provides a comprehensive overview of the current state of the Starry Map component and outlines the planned improvements and features. It serves as a solid foundation for your GitHub Pull Request and future development efforts.

### Issues

- fixes #1656

2024-08-04 20:48 UTC, ogerly commented
https://github.com/user-attachments/assets/dddc0863-1474-4c71-8850-7478039d157d

2024-08-05 11:09 UTC, Bettelstab requested changes
Content-wise good to be merged, thank you! Just please fix linting (`npm run test:lintfix` and after that, disabling linting for specific lines would be fine for me) and update the snapshot. Lower coverage if necessary...

2024-08-05 11:37 UTC, roschaefer requested changes
Same as @Bettelstab but I would also like to have a separate route for this:

![image](https://github.com/user-attachments/assets/fba296c4-7991-4be0-ac8e-40334a3d50bb)

2024-08-05 11:37 UTC, roschaefer commented on frontend/src/components/starry-map/StarryMap.vue
> +        }));
```suggestion
        stars.value = Array.from({ length: 200 }, (_, i) => {
          const id = id: i + 1
          const description = 'This is a virtual space. More information can be added here.'
          const left = `${Math.random() * 100}%`
          const top = `${Math.random() * 100}%`
          const pulsing = Math.random() < 0.1
          const randomIndex = Math.floor(Math.random() * starTypes.length)
          const type = starTypes[randomIndex]
          const text = type.charAt(0)
          const name = `${type} ${i + 1}`
          const users = Array.from({ length: Math.floor(Math.random() * 5) + 1 }, () => `User${Math.floor(Math.random() * 1000)}`),
          return { id, left, top, pulsing, type, text, name users }
        });
```

This ensures that we use the same `randomIndex` instead of re-evaluating.

2024-10-07 15:10 UTC, ogerly commented
old

2024-10-07 15:10 UTC, closed without merging