refactor: context hook
dreammall-earth/dreammall.earth pull request #1684
Opened 2024-08-07 23:49 UTC by roschaefer

Motivation
----------
This fixes #1503.

This is necessary before I can properly implement role based authorization (for the admins).

How to test
-----------
1. CI should be green

2024-08-07 23:52 UTC, roschaefer commented on backend/src/graphql/resolvers/UserResolver.ts
> -    if (data.availability === undefined) delete data.availability
This is something I don't understand: Why was the `updatedUser` not returned?

2024-08-14 10:42 UTC, Mogge requested changes
Nice refactor. Much better structured, and I like the context function. Please check for the false positive.
How do you want to realize the admin authorization? So far the single source of truth is authentik and therefore the token. When you touch the `authChecker` function, the token is already `out of scope.

2024-08-14 10:42 UTC, Mogge commented on backend/src/auth/authChecker.spec.ts
>  // uses joinMyTable query
```suggestion

2024-08-14 10:42 UTC, Mogge commented on backend/src/graphql/resolvers/UserResolver.spec.ts
> +        it('deletes introduction and availability', async () => {
This is a false positive as introduction and availability are already null.

2024-08-14 10:42 UTC, Mogge commented on backend/src/graphql/resolvers/UserResolver.ts
> -    if (data.availability === undefined) delete data.availability
When I wrote this code I was confused as well. Check if the false positive is workuing

2024-08-14 10:42 UTC, Mogge commented on backend/jest.config.json
> +      "branches": 79,
It would be nice to avoid the
```
    const { user } = context
    if (!user) throw new Error('User not found!')
```
construction in all resolvers that require a user. Can we somehow force the `type UserWithProfile`  for calls that require authorization?

2024-08-14 20:28 UTC, roschaefer commented
> Nice refactor. Much better structured, and I like the context function. Please check for the false positive. How do you want to realize the admin authorization? So far the single source of truth is authentik and therefore the token. When you touch the `authChecker` function, the token is already `out of scope.

Role based-authorization can be done with this: https://github.com/dreammall-earth/dreammall.earth/pull/1686/files#diff-ab0ffeecd111988f9570b4645447f2cf50e1aecc99eef4cc4d45fbfbe3314dcbR65 and we would create an admin group with `{ roles: ['admin'] }` attributes. Every member of this group will have the deep-merged roles in the JWT payload. Authentik has a concept of "roles" as well, but I could not find a documented way to encode that in the payload. I guess, group attributes are the way to go.

Also, I vote to decode the `JWT` in the backend and return the `currentUser.roles` to the frontend *without a database call* if not necessary. We can store the roles in the database, too, why not. But I would like to avoid a `findOrCreateBy` database call in the context hook unless we need to update/save the currentUser in our database.

2024-08-14 20:29 UTC, roschaefer commented on backend/src/graphql/resolvers/UserResolver.spec.ts
> +        it('deletes introduction and availability', async () => {
I will have a look into this, but is this a blocker for this PR?

2024-08-14 21:12 UTC, roschaefer commented on backend/src/graphql/resolvers/UserResolver.spec.ts
> +        it('deletes introduction and availability', async () => {
@Mogge it's addressed and certainly not a false negative anymore - I consider a failing test as positive (like a HIV-test) and a false positive a false alert. A false negative for me would be a test that does not fail but a bug is present.

2024-08-14 21:14 UTC, roschaefer commented on backend/jest.config.json
> +      "branches": 79,
Yes, I will also have a look but this is out of scope of this PR, isn't it?

Maybe there is a typescript solution for this. Ideally `Authorized()` would mark the `context.user` as not null.

2024-08-14 21:38 UTC, roschaefer commented on backend/jest.config.json
> +      "branches": 79,
@Mogge I think we're out of luck here: https://github.com/microsoft/TypeScript/issues/49229

I would suggest we use a simple helper method:
```ts
const { user } = requireUser(context)
```

with:
```ts
const requireUser = (context: Context) => {
  const { user } = context
  if (!user) throw new Error('context.user must be present after authorization!')
  return context
}
```

2024-08-15 07:32 UTC, Mogge commented on backend/jest.config.json
> +      "branches": 79,
This would not raise the coverage of our branches

2024-08-15 07:35 UTC, Mogge commented on backend/src/graphql/resolvers/UserResolver.spec.ts
> +        it('deletes introduction and availability', async () => {
Did you change something? There is only one force pushed commit and I cannot see the changes done by the last commit. Was I wrong? Now the code looks fine

2024-08-15 07:36 UTC, Mogge commented on backend/jest.config.json
> +      "branches": 79,
Could we have a dummy unauthenticated user that is set if there is no authentication?

2024-08-15 07:37 UTC, Mogge approved these changes
We can merge this for now.

2024-08-15 08:18 UTC, ulfgebhardt commented
@roschaefer pls do your thing

2024-08-15 09:23 UTC, merged