feature(frontend): add mutations for about me, update user store and user query
dreammall-earth/dreammall.earth pull request #1689
Opened 2024-08-09 11:28 UTC by Bettelstab

## 🍰 Pullrequest
- Adds mutations for adding and removing user details and social media accounts
- Adds a mutation to update availability and name of a user
- Modifies the user query to contain these informations
- Updates the user store, which now uses those mutations and exposes them as actions

Will be used by #1327.

### Issues
- fixes part of #1018

2024-08-09 15:05 UTC, roschaefer requested changes
I think this PR adds a lot of complexity that I would like to see refactored before we merge. I offer to do a pair-programming together, if you like.

![mutation](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTFqaTh2MWgydW85bTA0YW5jNHBsaTQ5dnQ0OG9vN2o5YmJsbWhhcyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l4Jz0ejsmBvLNIvuM/giphy.gif)

2024-08-09 15:05 UTC, roschaefer commented on frontend/src/stores/userStore.ts
> +export type UserDetailCategory = 'place' | 'work' | 'language' | 'education' | 'feeling'
Ideally these enums are auto-generated from the schema. There is tooling for that.

2024-08-09 15:05 UTC, roschaefer commented on frontend/src/stores/userStore.ts
> +        setCurrentUser({
Why do we have to do this manually?

2024-08-10 10:39 UTC, Bettelstab commented on frontend/scripts/tests/mock.apolloClient.ts
> +import { updateUserMutation } from '#mutations/updateUserMutation'
Good question. I'm not super experienced with GraphQL, but nested updates would require backend changes I guess. @Mogge were there specific reasons to do it like this, or do you think it could be changed?

2024-08-10 10:40 UTC, Bettelstab commented on frontend/src/graphql/mutations/updateUserMutation.ts
> +  mutation updateUser($data: UpdateUserInput!) {
Of course.

2024-08-10 10:51 UTC, Bettelstab commented on frontend/src/stores/userStore.spec.ts
> +        await userStore.addUserDetail({
That makes a lot of sense. I know that approach from another project with React and a data fetching library which did the caching and pagination, without stores. We probably can ditch the entire user store, adding a composable for the initials if necessary.

2024-08-13 21:02 UTC, roschaefer approved these changes
I will not block this from getting merged. But here are some little improvements which could be incorporated. Also, this branch needs to get merged/rebased on `origin/master`, I see conflicts.

There is no UI for this, right? I was about to check out the code locally.

2024-08-13 21:02 UTC, roschaefer commented on frontend/src/graphql/mutations/addSocialMediaMutation.ts
> +export const addSocialMediaMutation = gql`
BTW: I think `ALL_CAPS` is a naming convention for GraphQL documents.

2024-08-13 21:02 UTC, merged

2024-08-14 08:56 UTC, Bettelstab commented on frontend/src/stores/userStore.ts
> +    const { mutate: addUserDetailMutationResult } = useMutation<AddUserDetailMutationResult>(
I was about to do this in an extra PR, since this one got auto merged already.
But, in line 124 there is another `addUserDetailMutation`, so it doesn't work out.