[WIP] feat(front-end): table flows
dreammall-earth/dreammall.earth pull request #1743
Opened 2024-08-14 12:21 UTC by sebastian2357

## 🍰 Pullrequest

- This PR shows the current state of table flow development.
-  It is NOT ready for review! But feedback is more than welcome :)

### Issues

- [ ] GraphQL
- [ ] Dialoge for an active session
- [ ] Clean Up

2024-08-27 18:53 UTC, Bettelstab requested changes
I think there should be some adjustments code-wise.
But the most important, I have problems testing. User search does not work, and after I added my table, I get 500 from the frontend server.
Maybe my merge was bad, we need to check this in any case.

2024-08-27 18:53 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetup.vue
> +    @table-name:updated="updateTableName"
I wonder if `v-model=tableSettings` would do the trick.

2024-08-27 18:53 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetup.vue
> +  // window.history.pushState({ step }, '', url.toString())
I would like to try https://vike.dev/navigate#history-pushstate, but can be after we merge this PR.

2024-08-27 18:53 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetup.vue
> +const onBack = transitToPrevious
Why not `@next="transitToNext"`  ?

2024-08-27 18:53 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetupStepA.vue
> +const props = defineProps<TableSetupProps>()
```suggestion
defineProps<TableSetupProps>()
```

2024-08-29 21:53 UTC, Bettelstab requested changes
For me it's fine to merge all the new files as they are and to improve afterwards - under the given circumstances. But we should be careful with everything affecting existing code / being in existing files, because cleaning that afterwards is more difficult.

2024-08-29 21:53 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetupProps.ts
> +  (e: 'custom', stepId: string): void
I think 'goTo' would be a better name.

2024-08-29 21:53 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetupStepB.vue
> +.flat-text-field .v-field--variant-solo-filled {
Please change for clarity

2024-08-29 21:53 UTC, Bettelstab commented on frontend/src/stores/userStore.ts
> +        currentUser.value?.table || {
Can't it be null?

2024-08-29 21:53 UTC, Bettelstab commented on frontend/src/stores/userStore.ts
> +    const searchUsers = (name: string) => {
still here?!

2024-08-29 21:54 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetupProps.ts
> +  (e: 'custom', stepId: string): void
(optional for now)

2024-08-29 21:54 UTC, Bettelstab commented on frontend/src/stores/userStore.ts
> +        currentUser.value?.table || {
must have to clarify

2024-08-29 21:55 UTC, Bettelstab commented on frontend/src/panels/dreammall/TableSetupStepC.vue
> +<style lang="scss">
This should also be done before merging please

2024-08-29 22:07 UTC, sebastian2357 commented on backend/src/auth/authChecker.spec.ts
> +            meetingId: null,
it is a merge from moritz branch

2024-08-29 22:08 UTC, sebastian2357 commented on frontend/src/layouts/DefaultLayout.vue
> -      <MainButton
it is already removed

2024-08-29 22:09 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetupStepC.vue
> +      label="Suche"
done

2024-08-29 22:10 UTC, sebastian2357 commented on frontend/src/panels/PanelFlow.vue
> +<!--</script>-->
it prepared for the next refacotring to become a "base compoment". I commented it out, that it does not any effect to the remaining project.

2024-08-29 22:11 UTC, sebastian2357 commented on frontend/src/panels/PanelHeader.vue
> +        <v-icon>mdi-arrow-left</v-icon>
done

2024-08-29 22:11 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetup.vue
> +    @table-name:updated="updateTableName"
done

2024-08-29 22:11 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetup.vue
> +  // window.history.pushState({ step }, '', url.toString())
yes

2024-08-29 22:12 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetup.vue
> +    const users = tableSettings.value.users
done

2024-08-29 22:12 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetup.vue
> +// todo: hasOwnTable -> getOwnTable
removed

2024-08-29 22:12 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetupStepA.vue
> +const props = defineProps<TableSetupProps>()
done

2024-08-29 22:13 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetupStepB.vue
> +.flat-text-field .v-field--variant-solo-filled {
done

2024-08-29 22:14 UTC, sebastian2357 commented on frontend/src/panels/dreammall/TableSetupStepC.vue
> +<style lang="scss">
done

2024-08-29 22:17 UTC, sebastian2357 commented on frontend/src/panels/PanelHeader.vue
> +        <v-icon>mdi-close</v-icon>
done

2024-08-29 22:17 UTC, sebastian2357 commented on frontend/src/panels/dreammall/components/UserInvitationItem.vue
> +        {{ user.invited ? 'gesendet' : 'einladen' }}
done

2024-08-29 23:34 UTC, Bettelstab approved these changes

2024-08-29 23:39 UTC, merged