refactor(presenter): make input fields and checkbox reusable components
dreammall-earth/dreammall.earth pull request #180
Opened 2024-01-16 17:06 UTC by mahula

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-01-17 11:18 UTC, Mogge requested changes
```
 [vue-tsc] Property 'value' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<{ "onModelValue:update"?: ((value: boolean) => any) | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...> & { ...; }, never>; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T...'. 
```

2024-01-17 11:23 UTC, Mogge requested changes
* take snapshots of the new components
 * test that the update event is fired

2024-01-17 20:49 UTC, mahula commented
> * take snapshots of the new components
> * test that the update event is fired

Done

2024-01-18 06:24 UTC, Mogge approved these changes
Great work!

2024-01-18 06:27 UTC, Mogge requested changes

2024-01-18 06:27 UTC, Mogge commented on presenter/src/components/controls/DataPrivacyCheckbox.test.ts
> +    await wrapper.find('input[type="checkbox"]').trigger('change')
```suggestion
    await wrapper.find('input[type="checkbox"]').setValue(true)
```

2024-01-18 06:28 UTC, Mogge commented on presenter/src/components/controls/DataPrivacyCheckbox.test.ts
> +    await wrapper.find('input[type="checkbox"]').trigger('change')
https://test-utils.vuejs.org/api/#setValue

2024-01-18 13:36 UTC, Mogge requested changes
Please fix the warnings in the unit tests

2024-01-19 09:37 UTC, mahula commented
> Please fix the warnings in the unit tests

Done.

2024-01-19 09:44 UTC, ulfgebhardt requested changes
Works as expected.

- Why do you put `DataPrivacyCheckbox` in `controls` rather than `inputs`?
- All Stories are missing

2024-01-19 09:46 UTC, mahula commented
> * Why do you put `DataPrivacyCheckbox` in `controls` rather than `inputs`?

Because I see it more on the control side (checkboxes, radio buttons etc.) than as an input element.

2024-01-24 13:27 UTC, mahula commented
> Please fix the warnings in the unit tests

Done

2024-01-24 13:45 UTC, Elweyn reviewed
```
  Snapshots  2 obsolete
             ↳ src/components/sections/PlanningSection.test.ts
               · TimelineSection > renders 1
             ↳ src/components/menu/HeaderMenu.test.ts
               · TopMenu > renders three columns 1
```

2024-01-24 14:56 UTC, mahula commented
> ```
>   Snapshots  2 obsolete
>              ↳ src/components/sections/PlanningSection.test.ts
>                · TimelineSection > renders 1
>              ↳ src/components/menu/HeaderMenu.test.ts
>                · TopMenu > renders three columns 1
> ```

Fixed

2024-01-24 15:02 UTC, Elweyn submitted a review, later dismissed
Seems good for me!

2024-01-24 16:42 UTC, mahula commented on presenter/src/components/forms/NewsletterForm.vue
> +          <DataPrivacyCheckbox></DataPrivacyCheckbox>
Fixed

2024-01-24 16:42 UTC, mahula commented on presenter/src/components/forms/ContactForm.vue
> +          <DataPrivacyCheckbox></DataPrivacyCheckbox>
Fixed

2024-01-24 18:24 UTC, ulfgebhardt approved these changes

2024-01-24 19:02 UTC, merged