feat(backend): join table for own tables
dreammall-earth/dreammall.earth pull request #1869
Opened 2024-08-28 09:37 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-08-29 11:49 UTC, Mogge requested changes

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +      bibiUser = await findOrCreateUser({ nickname: 'bibi', name: 'Bibi Bloxberg' })
Why not `prisma.user.create` ? If you use this method, you trigger a lot more of things, than just having the user in the database. Do you need to authenticate as any of these users? If not, I would simply create them. This keeps also the event table cleam

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            expect.arrayContaining([
This softens the test, see above

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +          // await prisma.usersInMeetings.deleteMany()
```suggestion
```

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            expect.arrayContaining([
Softens the test. Here you can see the event triggered by `findOrCreateUser`

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it.skip('creates meeting in database', async () => {
Why skipped?

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            expect.arrayContaining([
May be we can delete all events at the start of the tests? So we see only the one we are interested in?

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            if (!user) return
What? This is a unit test! No if clause!

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            if (!bibi) return
????

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            const meeting = await prisma.meeting.create({
Why not using the API here?

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            await prisma.usersInMeetings.createMany({
I think you get the better result when calling the `createTable` mutation as user

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +          it('calls join meeting link with moderator pw for peter', async () => {
```suggestion
          it('calls join meeting link with attendee pw for peter', async () => {
```

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +      bibiUser = await findOrCreateUser({ nickname: 'bibi', name: 'Bibi Bloxberg' })
OK. No I saw, that you need to be bibi later. I suggest to clean up the event table after creating the users the first time. Then we would not have the `CREATE_USER` event in the database but only the ones we are interested in

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +          beforeEach(async () => {
Better before all?

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +    if (userIds) {
What happens when I want a public table with only myself as moderator? `userIds` is null or undefined, so you have a table without any user

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +      const inviteLink = new URL(`join-table/${table.id}`, CONFIG.FRONTEND_URL).toString()
Repeated code to create the invite link

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +    } else if (table.user && table.user.id === user.id) {
This should be an OR in the above if clause. When I join my table, it is or created? How could this pass the unit test?

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +  meeting: {
Why not type Meeting?

2024-08-29 11:49 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +const findUsersInMeetings = async (meeting: {
type Meeting?

2024-08-29 11:55 UTC, Mogge commented
We can only merge this, if https://github.com/dreammall-earth/dreammall.earth/pull/1743 is merged

2024-08-29 19:33 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it.skip('creates meeting in database', async () => {
Because I didn't know how to query the right information

2024-08-29 19:35 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.ts
> +    if (userIds) {
Good catch.

2024-08-29 21:22 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            expect.arrayContaining([
Yeah I wanted to try this but I would need a clearer mind to figure out how to do it well

2024-08-29 21:24 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +            await prisma.usersInMeetings.createMany({
Yes but since the table mutation is a bit complex it is not so easy to know whith which meetingId the call was triggered

2024-09-06 10:43 UTC, Mogge requested changes
Please create a refactor issue for the events. Did I guess the test correctly?

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        // user = await findOrCreateUser({ name, nickname })
```suggestion
```

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +        it('returns table with users', async () => {
```suggestion
        it('returns table with creating user as moderator', async () => {
```

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +      describe('own meeting as public', () => {
```suggestion
      describe('public table without given users', () => {
```

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +                  isPublic: false,
```suggestion
                  isPublic: true,
```

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +                    public: false,
```suggestion
                    public: true,
```

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> +                  tableId: 25,
```suggestion
                  tableId: -1,
```

2024-09-06 10:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +    if (userIds) {
```suggestion
    if (userIds.length) {
```
an empty array is true

2024-09-09 09:57 UTC, Mogge approved these changes

2024-09-09 10:25 UTC, merged