feat(presenter): double opt in
dreammall-earth/dreammall.earth pull request #188
Opened 2024-01-18 10:16 UTC by ulfgebhardt

## 🍰 Pullrequest

Defines the route `/optin/@code` which checks the given code and either shows an error with an link to resubscribe or shows a success message and automatically redirects to the main page after 5 secs.

### Issues

- fixes https://github.com/dreammall-earth/dreammall.earth/issues/164

### Todo

Uncovered code
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/322918c0-0855-4eb8-847c-3d1d336ba200)

2024-01-18 14:53 UTC, Mogge requested changes
```
3:52:16 PM [vike][request(24)] URL /optin/2ae4f265372fb56b doesn't match the route of any of your pages:
┌──────────────┬──────────────────┬─────────────────────────┐
│ ROUTE        │ TYPE             │ DEFINED BY              │
├──────────────┼──────────────────┼─────────────────────────┤
│ /            │ Filesystem Route │ /src/pages/index/       │
│ /datenschutz │ Filesystem Route │ /src/pages/datenschutz/ │
│ /impressum   │ Filesystem Route │ /src/pages/impressum/   │
└──────────────┴──────────────────┴─────────────────────────┘
See https://vike.dev/routing for more information about routing.
```

2024-01-18 15:07 UTC, Mogge commented
![image](https://github.com/dreammall-earth/dreammall.earth/assets/15882241/e3d65cc2-0d2a-48fd-8842-9055184f7eb2)

Looks terrifying. In success case as well

2024-01-18 19:25 UTC, Mogge commented on presenter/src/pages/optin/+Page.vue
> +      navigate('/')
@ulfgebhardt do yo agree that this is better?

2024-01-18 22:38 UTC, ulfgebhardt commented
Die unit tests terminieren nicht

2024-01-22 12:19 UTC, ulfgebhardt commented on presenter/src/locales/en.json
> +      "text": "Du hast dein Newsletterabbonoment erfolgreich bestätigt. Du wirst in Kürze auf die Startseite weitergeleitet."
Yes, we will have a complete translation when multi language is available

2024-01-22 12:25 UTC, Elweyn approved these changes

2024-01-22 12:25 UTC, merged