fix(frontend): each time fresh tables
dreammall-earth/dreammall.earth pull request #1940
Opened 2024-09-04 15:05 UTC by Bettelstab

## 🍰 Pullrequest
When a mall talk table (user's own table) already exists and he tries to create a new one, instead of throwing an error, the new table is created and the old one is deleted.

It was requested by @Hardy-Hart-am-Start (actually it was requested to always expose the table settings before entering the mall talk table and this is a way to solve this.) As a benefit, it also gets rid of any old chat in BBB, when I leave my table and later enter it again via the DreamMall button, which was requested by Sabine and Claudia.

### Todo
- [ ] Maybe write a test to check if the old table was actually deleted
- [ ] Test what happens when the table is deleted with active meeting

2024-09-05 07:39 UTC, roschaefer requested changes
![I like](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGU4eTdlbzV0c3R6cnVhMWkyOTU4ZG1iMjNiZ3NrMHNoc3B6dW04MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/eMDtF5OfTWnNwWy3Mo/giphy.gif)

I want to see this code merged, but before, I would like to see the backend code refactored :+1:

2024-09-05 07:39 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.ts
> +
I like the simplicity of this PR. :+1: we should always look for solutions that reduce complexity in the code.

What I don't understand is: Why delete the meeting instead of just returning it? If the user wants to update the meeting, we can find, update and return it, no?

You could rename the mutation, i.e. it's not only *create*.

2024-09-05 08:38 UTC, Bettelstab commented on backend/src/graphql/resolvers/TableResolver.ts
> +
Updating the existing meeting (table) was the approach which first came to my mind. I thought about it and the reasons I went for this solution instead:

- With updating, the ID and hence URL does not change, which means participants of the old meeting will possibly find themselves in a new one with an unrelated topic, which might lead to confusion. Same goes for guest links.
- There could be situations when there is an ongoing BBB meeting belonging to the BBB meeting. Than that would have to be closed first and created again with new settings. (That could be done, of course, but would not be less complex.)

Please tell me if that makes sense . I would also like to hear @mogge's opinion about it. For me, we can do it either way. And yes, we should then update the mutation name accordingly.

2024-09-05 08:43 UTC, Mogge requested changes
Please show in a unit test, that the existing meeting is deleted. What happens, when the meeting was private and has foreign keys in the UsersInMeeting Table?

2024-09-05 08:43 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.spec.ts
> -      describe('meeting exists', () => {
Please test the new behavior.

2024-09-05 08:49 UTC, Mogge commented
I am not sure if this is actually a good idea. Think of the case, that as user created his table as private and added manually a number of users, which takes a lot of time. Now he clicks on create my table again and all the hard work done adding users is gone. We have to assume that with more users on the app, the most users would turn their own table to private and add their friends to it. So this looks more like a bug to me than a feature.

2024-09-05 10:15 UTC, Mogge commented
Another point. The URL to join my room should be persistent or not? When deleting my table the URL changes.

2024-09-08 12:50 UTC, ulfgebhardt approved these changes
We decided to go for this and evaluate if the new behavior is a strong limitation to the MallTalk table or if we can keep it the new way.

2024-09-08 13:00 UTC, merged