Refactor dialogs
dreammall-earth/dreammall.earth pull request #1943
Opened 2024-09-04 19:12 UTC by Bettelstab

## 🍰 Pullrequest
Refactors the code of create my table and my table settings.

### Issues
- fixes #1908 

### Todo

## 🔧 Refactor
- [ ] Introduce a composable or component to encapsulate steps
- [ ] Maybe generalize `TableSetup` and its props and emits, or use generics
- [ ] Do we want to put async in function names of async functions? (Be consistent)
- [ ] Think about folder names: `panels/dreammall`?
- [ ] Move `copyToClipboard` to `utils` or similar
- [ ] Simplify join table: just navigate to table page

2024-09-08 13:20 UTC, ulfgebhardt commented on frontend/src/components/malltalk/setup/TableSetup.vue
> +import TableSetupStepD from './TableSetupStepD.vue'
I think it Would be wise to name the Steps based on what they do - this will increase readability - especially since I would expect that we will add steps or remove some.

2024-09-08 13:20 UTC, ulfgebhardt commented on frontend/src/components/malltalk/setup/TableSetupStepB.vue
> +./StepProps #src/panels/dreammall-button-drawer/interfaces/MyTableSettings.js
whats this?

2024-09-08 13:46 UTC, ulfgebhardt requested changes
Button has no more function:
![image](https://github.com/user-attachments/assets/595ea9a9-5821-4875-85ac-ae212516ebe5)

The Table name does not require an input
![image](https://github.com/user-attachments/assets/0b360a3b-5f62-4f04-9051-b4c363121b7c)

I want to challenge the default value:
![image](https://github.com/user-attachments/assets/c1bfb89d-295b-4913-8dda-14604b465351)
As Table name an Default like `Ulf's Table` could be useful - maybe its displayed as `placeholder` and only unsed when the user doesn't type anything in the table field
Why is a Table by default private? Is this because you change from `isPublic` to `isPrivate` - I believe an Table should be public by default.

2024-09-09 10:41 UTC, Bettelstab commented on frontend/src/components/malltalk/setup/TableSetupStepB.vue
> +./StepProps #src/panels/dreammall-button-drawer/interfaces/MyTableSettings.js
Seems to be some editor artifact. No idea. Removed it.

2024-09-09 10:54 UTC, ulfgebhardt commented
Just clicking through the dialog does this:
![image](https://github.com/user-attachments/assets/8eb36bf8-8f1e-4cd8-9581-102d7ddf92b6)

See: https://app.refactor-dialogs-deploy.git.dreammall.earth/

2024-09-09 14:14 UTC, ulfgebhardt approved these changes
Works for me

2024-09-09 14:14 UTC, merged