feat(backend): update table
dreammall-earth/dreammall.earth pull request #2028
Opened 2024-09-12 15:22 UTC by Elweyn

## 🍰 Pullrequest
On the cockpit my tables section we can change the name of a project table or add other moderators.
This creates the mutation and binds it to the frontend.

### Issues
- None

### Todo
- [X] None

2024-09-12 17:07 UTC, roschaefer requested changes
![rejected](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWh6aHVscHNwMG43eGF5OHdnZHZhc2hmNTc4cXNxcThnd3Q5MXZxbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7524u1GFWqtm8HXa/giphy.gif)

I'm sorry, but I won't approve this. Mainly because of the potential bug but also because of the scattered logic in the backend for the authorization.

I'm more than willing to do a pair-programming with you! :+1:

2024-09-12 17:07 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.ts
> +          public: isPublic,
That's strange, if I want to update `isPublic` I must supply `name`? I think this is a bug.

2024-09-12 17:07 UTC, roschaefer commented on backend/src/graphql/resolvers/TableResolver.ts
> +      })
I would be deeply disappointed if `prisma` has nothing in place for this.

2024-09-12 17:07 UTC, roschaefer commented on frontend/src/stores/tablesStore.ts
> +      }
`apollo-client` has a built-in cache. It updates every record by it's `type` and unique `id`. I. e. if the graphql server responds with a new record, then `apollo-client` will go ahead and already replace the record in the cache.

If you watch this state in a clever way, then you don't have to implement this code here at all.

2024-09-12 17:07 UTC, roschaefer commented on frontend/src/stores/tablesStore.ts
> +      }
I would love to have one `updateTable` for everything.

2024-09-17 09:05 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.ts
> +          public: isPublic,
You would prefer to make everything optional and update what is given?

2024-09-17 09:25 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.ts
> +    @Arg('name', () => String, { nullable: true }) name: string | null | undefined,
You would prefer this:
```
type SomePrismaImportedType = {
  name?: string | null | undefined,
  public?: boolean,
  userIds?: number[] | null | undefined,
}
```

2024-09-23 11:55 UTC, ulfgebhardt approved these changes
I'll do a followup ticket to make name optional and use one updateTable for everything

2024-09-23 12:49 UTC, merged