Delete user via authentik
dreammall-earth/dreammall.earth pull request #2258
Opened 2024-09-19 18:08 UTC by roschaefer

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-10-02 19:42 UTC, roschaefer commented on backend/.npmignore
> +**/*.spec.ts
Silly, this will prevent:
```
$ npm run test:lint:eslint -- --fix

/home/robert/Development/dreammall/dreammall.earth/backend/src/api/webhooks.spec.ts
  2:21  error  "supertest" is not published  n/no-unpublished-import
```

2024-10-03 17:47 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +    await prisma.usersInMeetings.deleteMany({ where: { userId } })
What if it is the last user in the meeting? The we have a meeting in the database that nobody can join?

2024-10-03 17:48 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +    await prisma.usersInMeetings.deleteMany({ where: { userId } })
See `deleteTable` in the table resolver. Which is more like leave table and delete the table if I am the last moderator on it

2024-10-07 10:39 UTC, Mogge requested changes
I hope I could explain where I want to go ...

2024-10-07 10:39 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +    if (meetingId) {
This is the simple case: the user owns a meeting, which now we call Mall Talk. This should be deleted in any case, as well as all the entries in the `userInMeetings` table for the given meeting id.
The case I was worrying about, is a group table: The user to be deleted has created a public table. Therefore one entry is created in the `userInMeetings` table, linking that user to the table. Now this table must be deleted as well when the user is deleted, as no one else will be able to open this table, as no one is left with moderator rights.

2024-10-07 10:39 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +      where: { pk },
```suggestion
      where: { pk },
      include: {
        meetings: true,
      },
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +      await deleteTable({ prisma, logger })({ userId, tableId: meetingId })
```suggestion
      await deleteTable({ prisma, logger })({ userId, tableIds: [...meetings.map((m) => m.id), meetingId ] })
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/graphql/resolvers/TableResolver.ts
> +    await deleteTable({ prisma, logger })({ userId: user?.id, tableId })
```suggestion
    await deleteTable({ prisma, logger })({ userId: user?.id, [tableId] })
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/use-cases/delete-table.ts
> +  async ({ userId, tableId }: { userId: number; tableId: number }) => {
```suggestion
  async ({ userId, tableId }: { userId: number; tableIds: number[] }) => {
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/use-cases/delete-table.ts
> +    const meeting = await prisma.meeting.findFirst({
```suggestion
    const meetings = await prisma.meeting.findFirst({
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/use-cases/delete-table.ts
> +        id: tableId,
```suggestion
        id: { in: tableId },
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/use-cases/delete-table.ts
> +    if (!meeting) {
And start here a for each block for the meetings

2024-10-07 10:39 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +    const { id: userId, meetingId } = deletedUser
```suggestion
    const { id: userId, meetingId, meetings } = deletedUser
```

2024-10-07 10:39 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +    await prisma.usersInMeetings.deleteMany({ where: { userId } })
This line should be done by `deleteTable`

2024-10-07 10:46 UTC, Mogge commented
We can pair over this PR to clarify things.

2024-10-08 08:39 UTC, Mogge requested changes
One small thing ...

2024-10-08 08:39 UTC, Mogge commented on backend/src/use-cases/leave-table.ts
> +      if (!meeting.users.some(oneElseIsModerator(userId))) {
Nice!

2024-10-08 08:39 UTC, Mogge commented on backend/src/api/Authentik/deleteUser.ts
> +      await prisma.meeting.deleteMany({ where: { id: meetingId } })
This may throw: The meeting can be private and have entries in the `usersInMeetings` table. So this will cause a database error as foreign constraint points to null.

2024-10-08 11:16 UTC, Mogge approved these changes
Now it is fine. Thank you!

2024-10-08 11:29 UTC, merged