fix(frontend): redirect after login
dreammall-earth/dreammall.earth pull request #2331
Opened 2024-09-23 20:48 UTC by Bettelstab

## 🍰 Pullrequest
When opening a link to e.g. `/table/5` in logged out state, now that path is stored as state of the oidc protocol and used to redirect the user there after successful sign in.

### Issues
- fixes #1881 

### Todo
Observe if it is necessary to pass the path in `apollo.ts` when backend sends `UNAUTHENTICATED`. (I did not implement it there because I could not think of a straight forward way to get `pageContext`.

2024-09-23 21:04 UTC, roschaefer requested changes
![query params](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExanNlNWJpa2Vud3RiN2J6Y3ZubTdjYTRnb2V1a2x2Nm5tZ2pkcnJpYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fUjauzDjbxd77fPyzp/giphy.gif)

2024-09-23 21:13 UTC, Bettelstab commented on frontend/src/services/AuthService.ts
> +      state: `/${pathname}`,
Not really, `state` is defined in the protocol. I could do something like:
`state: {
  redirectTo: '...',
}`
would you prefer that?

2024-09-23 22:00 UTC, roschaefer commented on frontend/src/services/AuthService.ts
> +      state: `/${pathname}`,
Yes, this is more telling.

2024-09-23 22:03 UTC, roschaefer commented on frontend/src/pages/+guard.ts
> +    throw redirect(`/signin?previousUrl=${pageContext.urlPathname}`)
Watch out for encoding issues with slashes. You could e.g. use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)

2024-09-26 20:42 UTC, ulfgebhardt approved these changes

2024-09-26 20:49 UTC, merged