fix(frontend) If you disallow cookies the page just shows errors
dreammall-earth/dreammall.earth pull request #2405
Opened 2024-09-26 14:39 UTC by trinity2701

## 🍰 Pullrequest

### Issues

- fixes #1737
- None

### Todo

- [X] None

2024-09-26 15:29 UTC, roschaefer requested changes
![cookies](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnQ0NndzM2RyM21qaGZpazZwNmlkdXg1N3YxZTFpODJ6cHp2NW4wbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/mJONUM663p4OZt3i5J/giphy.gif)

2024-09-26 15:29 UTC, roschaefer commented on frontend/renderer/app.ts
> +          toast.error('🍪 Please enabled cookies!', {
```suggestion
          toast.error('🍪 Please enable cookies!', {
```

2024-09-26 15:29 UTC, roschaefer commented on frontend/renderer/app.ts
> +      } catch {
It's never a great idea to catch-all errors, we even have a ticket for this: https://github.com/dreammall-earth/dreammall.earth/issues/1548

Could you check what's the error type when you disallow cookies?

2024-09-26 15:29 UTC, roschaefer commented on frontend/renderer/app.ts
> +          toast.error('🍪 Please enabled cookies!', {
It would be nice to translate this string.

2024-09-26 15:29 UTC, roschaefer commented on frontend/renderer/app.ts
> +          toast.error('🍪 Please enabled cookies!', {
And maybe it's better to write 
```suggestion
          toast.error('🍪 Please enable cookies in your browser!', {
```

2024-09-27 11:04 UTC, roschaefer requested changes
On chromium I'm not even able to disallow *all* cookies for any site. @trinity2701  How did you test it out?

2024-09-27 11:04 UTC, roschaefer commented on frontend/renderer/app.ts
> +        if (String(error).includes('SecurityError: Failed to read')) {
This is what I see on firefox (Mozilla Firefox 130.0.1):

![satty-20240927-13:01:22](https://github.com/user-attachments/assets/a98d58d6-9746-4925-82d8-529e6091791f)

2024-09-27 11:10 UTC, roschaefer commented on frontend/renderer/app.ts
> +      }
```suggestion
      try {
        provide('authService', new AuthService(pageContext.publicEnv.AUTH))
      } catch (error) {
        if (!error instancof WellKnownErrorClass) {
          throw error
        }
        toast.error(i18n.global.t('error.enablecookie'), {
          autoClose: false,
          closeButton: false,
          closeOnClick: false,
        })
      }
```

You also need to re-throw the error, if it's not the expected error!

2024-09-27 11:47 UTC, ulfgebhardt commented
> On chromium I'm not even able to disallow _all_ cookies for any site. @trinity2701 How did you test it out?

Yes you can do this.

To test this, login, disallow cookies from `app....` and delete existing cookie. This simulales the behaviour

2024-09-27 11:50 UTC, ulfgebhardt commented on frontend/renderer/app.ts
> +      }
@roschaefer I think here is the problem we cannot find the class of `Security Error` - thats some browser related stuff

2024-09-27 12:00 UTC, roschaefer commented on frontend/renderer/app.ts
> +      }
It's OK! Then use `String(error).includes('SecurityError: Failed to read')` I just guess it's different for different browsers.

Important is re-throwing the error if the condition doesn't match. It's a shortcoming of JavaScript that `catch(err)` does not filter for error classes and this is an eternal source of bugs.

2024-09-27 13:15 UTC, roschaefer approved these changes
@trinity2701 said to me on chat that she's not available today, so I quickly fixed the issues with multiple browsers in 7458ed53079f668e2c75890a20aaf4ac87f668cf

2024-09-27 13:17 UTC, roschaefer commented on frontend/renderer/app.ts
> +      }
@ulfgebhardt The error is documented here: https://developer.mozilla.org/en-US/docs/Web/API/DOMException#securityerror

2024-09-27 17:08 UTC, merged