[WIP] feat(backend): logging events
dreammall-earth/dreammall.earth pull request #244
Opened 2024-02-14 09:02 UTC by ulfgebhardt

## 🍰 Pullrequest

logging events

### Issues

- contributes to #143 

### Todo

- [ ] Test fixes
- [ ] Test for events to be written to database

2024-02-15 09:26 UTC, Elweyn reviewed
Seems good for me, lets just talk about the opened discussions.

2024-02-15 09:26 UTC, Elweyn commented on backend/src/graphql/inputs/ContactFormInput.ts
> +const MAX_CHARS_EMAIL = 254
Duplicate with inputs/SubscribeToNewsletterInput.ts consts.
Could be interessting to have it in one file for the case where we need to update it to other values

2024-02-15 09:26 UTC, Elweyn commented on backend/src/graphql/inputs/SubscribeToNewsletterInput.ts
> +const MAX_CHARS_EMAIL = 254
Duplicate with inputs/SubscribeToNewsletterInput.ts consts.
Could be interessting to have it in one file for the case where we need to update it to other values

2024-02-15 09:26 UTC, Elweyn commented on backend/src/graphql/resolvers/ContactFormResolver.ts
>    contactForm(): boolean {
Do we still need this query for the application?

2024-02-19 13:05 UTC, Mogge requested changes
Just some small improvement to a test

2024-02-19 13:05 UTC, Mogge commented on backend/src/graphql/resolvers/ContactFormResolver.spec.ts
> +        expect(sendContactEmails).toHaveBeenCalled()
```suggestion
        expect(sendContactEmails).toHaveBeenCalledWith({
          data: {
              firstName: 'Peter',
              lastName: 'Lustig',
              content: 'Hello DreamMall!',
              email: 'peter@lustig.de',
          },
        })
```

2024-02-19 13:05 UTC, Mogge commented on backend/test/helpers.ts
> +  await prisma.event.deleteMany()
No possible soft delete on events I suppose

2024-02-19 13:17 UTC, ulfgebhardt commented on backend/test/helpers.ts
> +  await prisma.event.deleteMany()
We will never delete events - there is no point in soft deletes here in my opinion

2024-02-19 14:03 UTC, Mogge approved these changes

2024-02-19 14:35 UTC, merged