refactor(frontend): remove global mocks in tests
dreammall-earth/dreammall.earth pull request #2444
Opened 2024-09-28 14:35 UTC by roschaefer

Motivation
----------
This removes the global mock of `oidc-client-ts`.

Mocking globally will affect *every* test and all of a sudden importing the module will behave differently. It is not explicitly done in the test that depend on the behaviour, adding confusion and potential for bugs.

This complexity is now refactored with good-old dependency injection. No need for mocks.

Furthermore, this tests collects every global mutation of `@vue/test-utils` in a single file to better communicate what to expect when you create a component wrapper with this framework.

How to test
-----------
1. `cd frontend && npm run test:unit -- --no-coverage`
2. Same same as before. But less code!

2024-09-28 14:51 UTC, roschaefer commented on frontend/renderer/app.ts
> +        })
I learned that this call will potentially throw `DOMException`.

2024-09-28 14:51 UTC, roschaefer commented on frontend/src/tests/mock.authService.ts
> +} satisfies ConstructorParameters<typeof AuthService>[0]['userManager']
I learned about `ConstructorParameters` in this PR: https://www.typescriptlang.org/docs/handbook/utility-types.html#constructorparameterstype

2024-10-01 00:15 UTC, ulfgebhardt requested changes
You break the cookie code just introduced by @trinity2701 
![image](https://github.com/user-attachments/assets/018e25ea-82c3-43c0-8e56-4d3e8cd022bd)

2024-10-01 09:17 UTC, roschaefer commented
> You break the cookie code just introduced by @trinity2701 ![image](https://private-user-images.githubusercontent.com/1238238/372281602-018e25ea-82c3-43c0-8e56-4d3e8cd022bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzQxMTAsIm5iZiI6MTcyNzc3MzgxMCwicGF0aCI6Ii8xMjM4MjM4LzM3MjI4MTYwMi0wMThlMjVlYS04MmMzLTQzYzAtOGU1Ni00ZDNlOGNkMDIyYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDFUMDkxMDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE1YTVlYjJlZDMzODY4MDAwMTU5YWU3YTAzYTQ5ZTRlMTUzMTU3MTcyNGI4ZWExYTcxNWQ5MDFmNjZlZWIyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FxrGMi_4PqVx_uJvODriBOde7xiRFDefiXaHQK0moqM)
> 
> Target: ![image](https://private-user-images.githubusercontent.com/1238238/372282673-ab7d6a90-168c-4dab-bc3e-312f4d1c9e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzQxMTAsIm5iZiI6MTcyNzc3MzgxMCwicGF0aCI6Ii8xMjM4MjM4LzM3MjI4MjY3My1hYjdkNmE5MC0xNjhjLTRkYWItYmMzZS0zMTJmNGQxYzllODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDFUMDkxMDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE2ZDM0NWJiZDE4ZGQ0ZjhlZTQ0MWI4MzMzMTVhNWVlNWRhMTE1ZjZiMzc3OWQ0ODdjM2NkODViZDExNjkwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ALREHa5syWrptXYTJYowvA7c_qPqSE0UdVbItRYTyIA)
> 
> I suggest to postpone this PR and continue on it as soon as we have released, since this does not contribute to the goal of the release

@ulfgebhardt actually I took care of that, see this comment: https://github.com/dreammall-earth/dreammall.earth/pull/2444/files#r1779513836

I don't know how I managed but I must have made a wrong merge conflict resolution here: 

![image](https://github.com/user-attachments/assets/2cede3ab-15e3-402f-8f64-f9cdb67f9e6d)

The reason for this PR is https://github.com/dreammall-earth/dreammall.earth/pull/2445 which we probably want to merge before the release.

2024-10-01 10:10 UTC, merged