Refactor pk in jwt
dreammall-earth/dreammall.earth pull request #2525
Opened 2024-10-01 14:22 UTC by roschaefer

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-10-01 14:31 UTC, ulfgebhardt commented on backend/prisma/migrations/20241001140736_add_pk_to_users/migration.sql
> +ALTER TABLE `User` ADD COLUMN `pk` INTEGER NOT NULL;
I think we might consider the id to be a string not an integer, considering that other pk-ids behave like uuids.

![image](https://github.com/user-attachments/assets/836bc84b-7684-40e2-a4f2-d20889b150d6)
https://docs.goauthentik.io/docs/events/

Furthermore I believe that a not null constraint will result in migration problems.

2024-10-01 15:31 UTC, roschaefer commented on backend/src/context/context.spec.ts
> +      it('crashes quite dramatically', async () => {
This is what happens if we forget our Authentik at `auth.dreammall.earth`.

2024-10-02 10:35 UTC, ulfgebhardt commented on backend/prisma/migrations/20241001140736_add_pk_to_users/migration.sql
> +ALTER TABLE `User` ADD COLUMN `pk` INTEGER NOT NULL;
Its fine with me to leave it like it is

2024-10-02 10:55 UTC, ulfgebhardt requested changes
Just doing `docker compose up database authentik backend frontend`

results in 
![image](https://github.com/user-attachments/assets/7b488089-5bcd-4de4-914a-1271ff5e35f6)

This results in a broken frotnend 
![image](https://github.com/user-attachments/assets/b7af15c1-70ec-4eb3-a020-ae8b7ec3757d)


`docker compose up database authentik backend frontend ---build` does not solve the problem
![image](https://github.com/user-attachments/assets/3aa593a4-d308-40e0-bd66-315f7e0c570f)

I'd like to have a solution for the developers before merging this

2024-10-02 11:35 UTC, ulfgebhardt approved these changes

2024-10-02 14:02 UTC, merged