refactor(backend): unauthenticated user object
dreammall-earth/dreammall.earth pull request #2536
Opened 2024-10-01 21:20 UTC by Mogge

Motivation: We have in our resolvers every time we fetch the user from the context a test, that the user exists.

This is because of the type definition of the user in the context, which may be null. To get rid of the if statements, I created an unauthenticated user object with id -1, that is put in the context when the user is not authenticated.
The coverage of branches is now 9% higher, and we do not have that useless code anymore.

Please check for any authentication issues.

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-10-01 23:41 UTC, roschaefer requested changes
![sorry](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHZ6dG10YjAyODA1M3kwemVtYnVmYmk3eTRzOG1wcG5odDI2ZWVnYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5t60PnbG1l2IhMFAIH/giphy.gif)

I'm sorry, but this is quite a hack. I like that we want to get rid of the if-clauses though! But I think it's much easier and cleaner, if we simply use a different type for the context argument.

2024-10-01 23:41 UTC, roschaefer commented on backend/src/context/context.ts
>  }
My suggestion is to simply create an:
```ts
export type AuthorizedContext = {
  user: UserWithProfile
// ...
```

And use this in our authorized resolvers:
```ts
  @Authorized()
  @Mutation(() => Int)
  async joinMyTable(@Ctx() context: AuthorizedContext): Promise<number> {
  // ...
```
 That should fix our typescript issues.

2024-10-03 12:48 UTC, Mogge commented on backend/src/context/context.ts
>  }
Thanks for the hint. Please have a look again

2024-10-07 10:51 UTC, Mogge commented
@roschaefer May you have a look again?

2024-10-07 12:01 UTC, roschaefer approved these changes
![typescript](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHVmbmtkaDA1ZDZ1a2d6eTdyYzh1M3lkcmMzMHU0N2phdDJ3bnQ5OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oKIPnAiaMCws8nOsE/giphy.gif)

Feel free to incorporate the suggestion or not.

2024-10-07 12:10 UTC, merged