feat(backend): subscription to calls you are invited
dreammall-earth/dreammall.earth pull request #2614
Opened 2024-10-07 05:41 UTC by Elweyn

## 🍰 Pullrequest

Motivation
---
As user I want to be informed that I am invited to a call so that I can join it if I am present

Solution
---
Create a subscription that returns a InvitedTable object so it can be shown in the frontend

### Issues

- fixes #2229

### Todo

- [X] None

2024-10-07 12:05 UTC, Mogge requested changes

2024-10-08 07:56 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/TableResolver.ts
> +      })
You do not test this to be called

2024-10-08 07:56 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/TableResolver.ts
> +  }
This code is untested

2024-10-08 07:56 UTC, ulfgebhardt commented on frontend/src/graphql/subscriptions/callSubscription.ts
> +    inviteCall {
I do not understand how the subscription is properly assigned to `inviteCall` - how does this correlate to `'CALL_SUBSCRIPTION'` defined above?

2024-10-08 10:54 UTC, Elweyn commented on backend/src/graphql/resolvers/TableResolver.ts
> +    if (!user) return null
Right

2024-10-08 12:45 UTC, ulfgebhardt approved these changes
Lets merge this and solve the test problem in another part: https://github.com/dreammall-earth/dreammall.earth/issues/2642

2024-10-09 04:58 UTC, merged