feat(other): dependabot for npm on root
dreammall-earth/dreammall.earth pull request #275
Opened 2024-02-25 01:42 UTC by ulfgebhardt

## 🍰 Pullrequest

dependabot for npm on root

This PR introduces dependabot updates for npm on root

### Issues

- None

### Todo

- [X] None

2024-02-25 09:27 UTC, mahula requested changes

2024-02-25 09:27 UTC, mahula commented on README.md
>  | `npx npm-check-update`     | Check for updates                              |
This entry is double.
We should stick to the `npm run <command>` pattern here.
Plese just keep the  `npm run update` entry.

2024-02-25 22:40 UTC, ulfgebhardt commented on README.md
>  | `npx npm-check-update`     | Check for updates                              |
very good catch! ❤️

2024-02-26 05:58 UTC, mahula approved these changes

2024-02-26 09:44 UTC, merged