add fill currentColor to svg phat
dreammall-earth/dreammall.earth pull request #2802
Opened 2024-10-21 08:26 UTC by ogerly

## 🍰 Pullrequest

I have added svgś in to all of them and reduced the displayed size of all of them slightly
```` ... <path fill="currentColor" ....````

### Issues
- fixes #2524 

![Bildschirmfoto vom 2024-10-21 09-14-38](https://github.com/user-attachments/assets/6f8a881a-0ad3-4c3d-a9a9-a910d3f79b06)
![Bildschirmfoto vom 2024-10-21 09-14-22](https://github.com/user-attachments/assets/4b438b55-0d8f-40a1-8eb2-9820039c41e2)

2024-10-22 09:36 UTC, Bettelstab requested changes
The icons are not centered in their viewbox, so they appear slightly off. Please cut the whitespace.

2024-10-23 08:53 UTC, ogerly commented
![Bildschirmfoto vom 2024-10-23 10-51-01](https://github.com/user-attachments/assets/708ba8e6-6ce5-46de-84b4-880b77c03fba)
![Bildschirmfoto vom 2024-10-23 10-50-46](https://github.com/user-attachments/assets/d70956cc-4002-435c-95e2-b9e7c336f311)
![Bildschirmfoto vom 2024-10-23 10-04-10](https://github.com/user-attachments/assets/0ecbcb6c-7cc5-41ac-acc9-480bbda8d3f5)
![Bildschirmfoto vom 2024-10-23 10-03-59](https://github.com/user-attachments/assets/ebce8d01-c4c4-47a2-b29b-6d52c53bd22e)
![Bildschirmfoto vom 2024-10-23 10-03-50](https://github.com/user-attachments/assets/f0a63bc3-1385-4977-867f-f6170c34beb6)
![Bildschirmfoto vom 2024-10-23 10-03-37](https://github.com/user-attachments/assets/89a74181-c820-4447-8bba-5cafbdab522e)

i have replaced the v-img with the svg so that the dark/light mode works.

2024-10-28 15:06 UTC, Bettelstab requested changes
Please remove unused code otherwise good to go! Thank you :)

2024-10-28 15:06 UTC, Bettelstab commented on frontend/src/components/cockpit/about-me/AboutMeView.vue
> +.social-icon {
Class is not longer used, please remove

2024-10-29 06:41 UTC, ogerly commented on frontend/src/components/cockpit/about-me/AboutMeView.vue
> +.social-icon {
removed

2024-10-29 08:05 UTC, Bettelstab approved these changes

2024-10-29 10:04 UTC, merged