refactor(frontend): remove MainButton and the sass it was using
dreammall-earth/dreammall.earth pull request #2990
Opened 2024-11-04 13:03 UTC by Bettelstab

## 🍰 Pullrequest
Removes the unused MainButton component.

2024-11-06 13:00 UTC, sebastian2357 requested changes

2024-11-06 16:15 UTC, Bettelstab commented on frontend/src/components/buttons/DreamMallButton.vue
> +  @media #{map.get(variables.$display-breakpoints, 'xs')} {
I like your suggestion, however, we are using the syntax  I used here at many other places already. So feels out of scope for this PR?

2024-11-11 08:57 UTC, sebastian2357 approved these changes

2024-11-11 09:42 UTC, sebastian2357 approved these changes

2024-11-11 09:42 UTC, merged