[WIP] feat(presenter): make i18n for page titles
dreammall-earth/dreammall.earth pull request #335
Opened 2024-03-14 16:57 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-03-22 17:14 UTC, ulfgebhardt reviewed
This looks very good. Please check if you can unify the language defintions so that it wold be easier to add new languages.
If this is a big overhead which prevents merging, we can merge it and have a new task for that.

2024-03-26 09:11 UTC, ulfgebhardt commented on presenter/src/components/language/LanguageSelector.vue
> +}
Why do you not use the model approach as before and make two functions instead? Whats the benefit?

2024-03-26 09:14 UTC, ulfgebhardt commented on presenter/locales/extractLocale.ts
> +  } else {
```suggestion
  if (locales.includes(firstPath)) {
    locale = firstPath
    urlWithoutLocale = '/' + urlPaths.slice(2).join('/')
  } else {
```

This fixes that `http://localhost:3000/de/impressum` is not recognized

2024-03-26 09:21 UTC, ulfgebhardt commented on presenter/renderer/+onBeforeRoute.ts
> +  }
```suggestion
```

2024-03-26 09:41 UTC, ulfgebhardt requested changes
A further test revealed that page navigation loses the locale.

If you are on `http://localhost:3000/en/impressum` and navigate to `http://localhost:3000/` locale is de again. This is actually an regression from previous functionality where the locale set in the browser was preserved.

2024-03-26 10:21 UTC, Elweyn commented on presenter/src/components/language/LanguageSelector.vue
> +}
Has been reverted to the same logic as before and fixes the other problem

2024-03-26 12:40 UTC, ulfgebhardt approved these changes

2024-03-26 12:40 UTC, merged