feat(frontend): authorization frontend
dreammall-earth/dreammall.earth pull request #404
Opened 2024-03-27 10:06 UTC by Mogge

## 🍰 Pullrequest

### Issues
- fixes #370

### Todo

- [X] None

2024-03-28 09:04 UTC, Elweyn reviewed
Seems good but could not test it...

2024-03-28 10:18 UTC, Elweyn submitted a review, later dismissed
I can't let it run with docker but if I change ``presenter/server/index.ts`` to default port 3001 then I test it with:
- cd authentik && docker compose up
- cd frontend && npm run dev || prod
- cd presenter && npm run dev || prod

The logic works fine

2024-03-28 10:57 UTC, ulfgebhardt requested changes
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/7fea5ea7-94c4-427d-9355-260194ddd6e3)

The guard throws serious errors - I am fine with merging this and resolve it after - but there is a problem.

2024-03-28 11:02 UTC, ulfgebhardt reviewed
The page /signin contains the signout button. This button must be reactive to the logged in state and not visible when not logged in (can be postponed)

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/d60a26f9-8b96-4781-ae51-fd13f8b1a8b1)

2024-03-28 11:06 UTC, ulfgebhardt reviewed
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/db85b351-7271-411f-98bb-b0f0a604ea36)

I think we should require correct values for this - maybe we want so set a default here, since the frontend only makes sense to operate when authentication is possible.
Furthermore the default values for

```
 AUTHORITY: (import.meta.env.PUBLIC_ENV__AUTH__AUTHORITY ?? '') as string,
  AUTHORITY_SIGNUP_URI: (import.meta.env.PUBLIC_ENV__AUTH__AUTHORITY_SIGNUP_URI ?? '') as string,
```
make no sense anymore, since the presenter hides its buttons, not the frontend

Furthermore `AUTHORITY_SIGNUP_URI` is not needed in the frontend.

2024-03-28 12:17 UTC, Mogge commented on presenter/src/components/menu/HeaderMenu.vue
> +  window.location.href = AUTH.SIGNIN_REDIRECT_URI
Yes

2024-03-28 12:17 UTC, Mogge commented on presenter/src/components/menu/HeaderMenu.vue
> +   */
Is removed in the next PR

2024-03-28 13:32 UTC, ulfgebhardt commented
> ![image](https://private-user-images.githubusercontent.com/1238238/317702169-db85b351-7271-411f-98bb-b0f0a604ea36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzIwODksIm5iZiI6MTcxMTYzMTc4OSwicGF0aCI6Ii8xMjM4MjM4LzMxNzcwMjE2OS1kYjg1YjM1MS03MjcxLTQxMWYtOThiYi1iMGYwYTYwNGVhMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTMxNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgxYzhlYWZlYjg5ZTkxNDE3OWZhMGYwN2UwODQ1OWI0Y2U0N2ZjYzRiYTRlYTQ1M2Q0YWRhNWJkMGVlMjVjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Kw1D7VVsryFgtiH_ZNku58rGKgu5-csKeb_95IsHbjE)
> 
> I think we should require correct values for this - maybe we want so set a default here, since the frontend only makes sense to operate when authentication is possible. Furthermore the default values for
> 
> ```
>  AUTHORITY: (import.meta.env.PUBLIC_ENV__AUTH__AUTHORITY ?? '') as string,
>   AUTHORITY_SIGNUP_URI: (import.meta.env.PUBLIC_ENV__AUTH__AUTHORITY_SIGNUP_URI ?? '') as string,
> ```
> 
> make no sense anymore, since the presenter hides its buttons, not the frontend
> 
> Furthermore `AUTHORITY_SIGNUP_URI` is not needed in the frontend.

Fixed - I kept the `AUTHORITY_SIGNUP_URI` since that would cripple the authService if not present.

2024-04-02 15:36 UTC, ulfgebhardt requested changes
Still doesn't work in production.

While I can see it working in dev, I don't get it to work on production.

Running on dev I can see the redirect happening on console and browser.

```
npm install
npm run dev
```

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/9e321f52-bff6-48a5-9e9f-dbad839638c3)
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/d331e155-a241-4510-956c-e9ebe0478796)
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/e9132e6c-7770-4389-ab8e-f130c8807daf)

In production nothing happens neither on console nor in the the browser

```
npm install
npm build
npm run server:prod
```

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/c47f12ea-d35b-4c9a-a466-153fe9dac55a)

2024-04-03 08:44 UTC, Mogge commented
Looks like a build problem to me. The guard does not trigger at all all when building for production. If I remove all the code and just leave a console, no output is seen anywhere

2024-04-04 18:57 UTC, ulfgebhardt approved these changes

2024-04-04 18:57 UTC, merged