feat(presenter): remove auth service
dreammall-earth/dreammall.earth pull request #406
Opened 2024-03-28 07:33 UTC by Mogge

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-04-08 08:40 UTC, Elweyn requested changes
There is a Problem in the following szenario:
- Going on presenter localhost:3001
- Sign in
- redirect to frontend localhost:3000
- call localhost:3001
- go back to localhost:3000 here we get redirected to localhost:3001 as if we are not signed in

2024-04-08 11:08 UTC, Mogge commented
This is the behavior on master. Has nothing to do with this PR.

2024-04-08 11:33 UTC, Mogge commented
Furthermore I think that this behavior is correct

2024-04-08 19:58 UTC, ulfgebhardt commented on presenter/.env.dist
>  PUBLIC_ENV__AUTH__AUTHORITY="http://localhost:9000/application/o/dreammallearth/"
what we need this for?

```suggestion
```

2024-04-08 19:58 UTC, ulfgebhardt commented on presenter/.env.dist
>  PUBLIC_ENV__SIGNIN_REDIRECT_URI="http://localhost:3000/signin"
i'd like if we can find a naming convention for both redirect urls

2024-04-08 19:58 UTC, ulfgebhardt commented on presenter/src/components/menu/HeaderMenu.vue
>  const showAuthentication = AUTH.AUTHORITY && AUTH.AUTHORITY_SIGNUP_URI
```suggestion
const showAuthentication = AUTH.AUTHORITY_SIGNUP_URI
```

2024-04-08 19:58 UTC, ulfgebhardt commented on presenter/src/components/menu/HeaderMenu.vue
>        <div v-if="showAuthentication" class="">
We must show the correpsonding button only when the url is given. If the url is missing, dont show the button. There should be two checks accordingly.

2024-04-08 19:58 UTC, ulfgebhardt commented on presenter/src/env.ts
>    AUTHORITY: (import.meta.env.PUBLIC_ENV__AUTH__AUTHORITY ?? '') as string,
remove
```suggestion
```

2024-04-08 19:58 UTC, ulfgebhardt commented on presenter/src/env.ts
>    SIGNIN_REDIRECT_URI: (import.meta.env.PUBLIC_ENV__SIGNIN_REDIRECT_URI ??
unify naming

2024-04-09 09:49 UTC, ulfgebhardt commented on presenter/.env.dist
>  PUBLIC_ENV__SIGNIN_REDIRECT_URI="http://localhost:3000/signin"
is this correct? You reference `SIGNIN_URI` not `SIGNIN_REDIRECT_URI` below

2024-04-09 14:17 UTC, Mogge commented on presenter/.env.dist
>  PUBLIC_ENV__SIGNIN_REDIRECT_URI="http://localhost:3000/signin"
Good catch!

2024-04-09 17:02 UTC, ulfgebhardt approved these changes

2024-04-09 18:08 UTC, merged