bug(docu): change link of deployment description
dreammall-earth/dreammall.earth pull request #924
Opened 2024-05-23 18:11 UTC by Elweyn

## 🍰 Pullrequest
As developer I want to see the documentation of the deployment.

### Issues
- None

### Todo

- [X] Link to deployment README.md
- [X] Bare-metal installation on root

2024-05-24 07:49 UTC, Mogge requested changes
Add frontend and admin as well to update backend url

2024-05-24 07:49 UTC, Mogge commented on deployment/README.md
> +```
This must be done for frotend and admin as well

2024-05-27 14:30 UTC, Mogge requested changes

2024-05-27 14:30 UTC, Mogge commented on deployment/README.md
> +### Configure backend connection
```suggestion
### Configure backend connections

#### Presenter
```

2024-05-27 14:30 UTC, Mogge commented on deployment/README.md
> +### Configure frontend connection
```suggestion
#### Frontend
```

2024-05-27 14:30 UTC, Mogge commented on deployment/README.md
> +### Configure admin connection
```suggestion
#### Admin
```

2024-05-31 10:37 UTC, mahula approved these changes
Good job!

2024-05-31 10:38 UTC, merged