feat(backend): send newsletter contact from backend to brevo
dreammall-earth/dreammall.earth pull request #98
Opened 2023-12-18 13:40 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- fixes #97 

### Todo

- [ ] Create method to send to brevo
- [ ] Use it
- [ ] Unit Test

2023-12-19 15:56 UTC, Mogge requested changes

2023-12-19 15:56 UTC, Mogge commented on backend/src/api/NewsletterBrevo.spec.ts
> +config.BREVO_CONTACT_LIST_ID = 1
```suggestion
config.BREVO_CONTACT_LIST_ID = 3
```

2023-12-19 15:56 UTC, Mogge commented on backend/src/api/NewsletterBrevo.spec.ts
>  console.log = consoleLogMock
No good idea. How can you debug while this is active?

2023-12-19 15:56 UTC, Mogge commented on backend/src/api/NewsletterBrevo.spec.ts
> +        it('calls the console.log in error path', () => {
I guess we do not want this in production

2023-12-19 15:56 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +export const createBrevoContactsApi = () => {
Dupliacate code. Same in ContactFormResolver

2023-12-19 15:56 UTC, Mogge commented on backend/src/api/NewsletterBrevo.spec.ts
> +          listIds: [1],
```suggestion
          listIds: [3],
```

2023-12-19 15:56 UTC, Mogge commented on backend/src/api/NewsletterBrevo.spec.ts
> +            listIds: [1],
```suggestion
            listIds: [3],
```

2023-12-19 15:56 UTC, Mogge commented on backend/src/graphql/resolvers/ContactFormResolver.ts
> +    if (promise) {
Why did this move here? This way it is not even tested that the DB is updated, or not in case of failure.

2023-12-19 15:56 UTC, Mogge commented on backend/src/graphql/resolvers/NewsletterSubscriptionResolver.ts
> +    if (promise) {
I would expect this in the Brevo API, and tested there

2023-12-19 16:07 UTC, ulfgebhardt commented on backend/src/api/NewsletterBrevo.spec.ts
>  console.log = consoleLogMock
Not my doing

2023-12-19 16:08 UTC, ulfgebhardt commented on backend/src/api/NewsletterBrevo.spec.ts
> +        it('calls the console.log in error path', () => {
not my doing

2023-12-19 16:08 UTC, Mogge requested changes

2023-12-19 16:08 UTC, Mogge commented on backend/src/graphql/resolvers/ContactFormResolver.ts
> +    if (promise) {
Is the database updated twice now?

`sendSmtpEmail` updates the database. So why do it again?

2023-12-19 16:08 UTC, Mogge commented on backend/src/graphql/resolvers/NewsletterSubscriptionResolver.ts
> +    if (promise) {
It i not tested that the DB is updated!

2023-12-19 16:08 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +      lastname: contactForm.lastName,
Why this change? Does the brevo template need the params like this?

2023-12-19 16:09 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/ContactFormResolver.ts
> +    if (promise) {
We decouple the remote call from the response for the user this way. We do not wait for the promise, but if its fulfilled we write things into the database.

2023-12-19 16:25 UTC, Elweyn commented on backend/src/api/NewsletterBrevo.ts
> +      lastname: contactForm.lastName,
I set it like this cause I tested the sending of emails with this param definition and I didn't want to change it in last minute and risk that it does work.

2023-12-19 16:25 UTC, Elweyn commented on backend/src/graphql/resolvers/NewsletterSubscriptionResolver.ts
> +    if (promise) {
OK

2023-12-19 17:42 UTC, Mogge requested changes
You have to remove the database update in send email. Now the database is updated three times.

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +    await sendAllEmail.then(() => {
```suggestion
  try {
    await Promise.all([sendEmailAdmin, sendEmailClient])
```

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +    await sendAllEmail.then(() => {
No then needed

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +    await promise.then(async () => {
```suggestion
  try {
    await apiInstance.createContact(createContact)
```

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +    await promise.then(async () => {
No then needed

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +      void prisma.contactForm.update({
```suggestion
      await prisma.contactForm.update({
```

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +      return undefined
```suggestion
```

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.ts
> +      return undefined
```suggestion
```

2023-12-19 17:42 UTC, Mogge commented on backend/src/api/NewsletterBrevo.spec.ts
> +      describe('without brevo key', () => {
Missing case for brevo rejects. Should not update the database. May be a follow up issue

2023-12-19 18:01 UTC, Elweyn commented on backend/src/api/NewsletterBrevo.spec.ts
> +      describe('without brevo key', () => {
https://github.com/dreammall-earth/dreammall.earth/issues/120

2023-12-19 18:05 UTC, Mogge submitted a review, later dismissed
```
export const sendSmtpEmail = async (
  smtpEmail: SibApiV3Sdk.SendSmtpEmail,
): Promise<ReturnType<SibApiV3Sdk.TransactionalEmailsApi['sendTransacEmail']> | undefined> => {
  const apiInstance = createBrevoInstance()
  try {
    const apiResponse = await apiInstance.sendTransacEmail(smtpEmail)
    return apiResponse
  } catch (error) {
    // TODO: logging or event
  }
}
```
This is not working with the promises. Please test with rejected response of `sendTranacEmail` that the database is _not_ updated

2023-12-19 18:05 UTC, Mogge commented on backend/src/graphql/resolvers/NewsletterSubscriptionResolver.ts
> +    void sendContactToBrevo(subscriber)
Not tested. This is easy, see Contact Form Resolver

2023-12-19 18:13 UTC, Elweyn commented on backend/src/graphql/resolvers/NewsletterSubscriptionResolver.ts
> +    void sendContactToBrevo(subscriber)
Has been added!

2023-12-19 22:03 UTC, ulfgebhardt reviewed
I guess we can merge it if its working

2023-12-20 08:21 UTC, ulfgebhardt approved these changes

2023-12-20 08:23 UTC, merged